package io.quarkiverse.permuplate.example.drools;

/**
 * Single-entry-point consumer: {@code accept(DS ctx, A a)}.
 * Consumer2..7 are generated by {@code FunctionalTemplate1}.
 */
@FunctionalInterface
public interface Consumer1<DS, A> {
    void accept(DS ctx, A a);
}
