package io.quarkiverse.permuplate.example.drools;

/**
 * Single-entry-point predicate: {@code test(DS ctx, A a)}.
 * Predicate2..7 are generated by {@code FunctionalTemplate1}.
 */
@FunctionalInterface
public interface Predicate1<DS, A> {
    boolean test(DS ctx, A a);
}
