package io.quarkiverse.permuplate.intellij.safedelete;

import com.intellij.psi.*;
import com.intellij.psi.search.GlobalSearchScope;
import com.intellij.testFramework.fixtures.BasePlatformTestCase;

import java.util.Collection;

public class PermuteSafeDeleteDelegateTest extends BasePlatformTestCase {

    private final PermuteSafeDeleteDelegate delegate = new PermuteSafeDeleteDelegate();

    // Test: delegate handles a class the index knows is generated
    public void testHandlesGeneratedClass() {
        // Callable1 is the template; index will compute Callable2..Callable10 as generated
        myFixture.addFileToProject("Callable1.java",
                "package io.example;\n" +
                "import io.quarkiverse.permuplate.Permute;\n" +
                "@Permute(varName=\"i\", from=\"2\", to=\"10\", className=\"Callable${i}\")\n" +
                "public interface Callable1 {}");

        // Add a stub Callable2 so we have a PsiClass to pass to the delegate
        myFixture.addFileToProject("Callable2.java",
                "package io.example;\n" +
                "public interface Callable2 { void call(Object o1, Object o2); }");

        PsiClass callable2 = findClass("io.example.Callable2");
        assertNotNull("Callable2 class must be findable", callable2);

        // The reverse index maps "Callable2" → "Callable1" via the @Permute on Callable1
        assertTrue("delegate should handle Callable2 (it is a generated class)",
                delegate.handlesElement(callable2));
    }

    // Test: conflict message for generated class mentions the template and "generated by Permuplate"
    public void testConflictMessageForGeneratedClass() {
        myFixture.addFileToProject("Callable1.java",
                "package io.example;\n" +
                "import io.quarkiverse.permuplate.Permute;\n" +
                "@Permute(varName=\"i\", from=\"2\", to=\"10\", className=\"Callable${i}\")\n" +
                "public interface Callable1 {}");

        myFixture.addFileToProject("Callable2.java",
                "package io.example;\n" +
                "public interface Callable2 { void call(Object o1, Object o2); }");

        PsiClass callable2 = findClass("io.example.Callable2");
        assertNotNull(callable2);

        Collection<String> conflicts = delegate.findConflicts(callable2, PsiElement.EMPTY_ARRAY);

        assertFalse("should produce a conflict for a generated class", conflicts.isEmpty());
        String message = conflicts.iterator().next();
        assertTrue("conflict should mention 'generated by Permuplate'",
                message.toLowerCase().contains("generated by permuplate") ||
                message.toLowerCase().contains("generated"));
        assertTrue("conflict should name the template",
                message.contains("Callable1"));
    }

    // Test: conflict message for template class lists generated family
    public void testConflictMessageForTemplateClass() {
        myFixture.addFileToProject("Callable1.java",
                "package io.example;\n" +
                "import io.quarkiverse.permuplate.Permute;\n" +
                "@Permute(varName=\"i\", from=\"2\", to=\"4\", className=\"Callable${i}\")\n" +
                "public interface Callable1 {}");

        PsiClass callable1 = findClass("io.example.Callable1");
        assertNotNull(callable1);

        Collection<String> conflicts = delegate.findConflicts(callable1, PsiElement.EMPTY_ARRAY);

        assertFalse("should produce a conflict for a template class", conflicts.isEmpty());
        String message = conflicts.iterator().next();
        assertTrue("conflict should mention generated family members",
                message.contains("Callable2") || message.contains("Callable3") || message.contains("Callable4"));
    }

    // Test: non-Permuplate class produces no conflict
    public void testNoConflictForPlainClass() {
        myFixture.configureByText("Foo.java", "public class Foo {}");
        PsiJavaFile file = (PsiJavaFile) myFixture.getFile();
        PsiClass foo = file.getClasses()[0];

        assertFalse("plain class should not be handled", delegate.handlesElement(foo));
        Collection<String> conflicts = delegate.findConflicts(foo, PsiElement.EMPTY_ARRAY);
        assertTrue("plain class should produce no conflicts", conflicts.isEmpty());
    }

    private PsiClass findClass(String fqn) {
        return com.intellij.psi.JavaPsiFacade.getInstance(getProject())
                .findClass(fqn, GlobalSearchScope.projectScope(getProject()));
    }
}
