package io.quarkiverse.permuplate;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Explicitly controls the return type of a method for each permutation value.
 *
 * <p>
 * <b>Not needed in the common case</b> (inline/Maven plugin mode with {@code T${j}} naming):
 * when the return type is a generated class whose type arguments follow the {@code T${j}}
 * naming convention, the return type and any undeclared parameter types are inferred
 * automatically — no annotation required.
 *
 * <p>
 * Use {@code @PermuteReturn} when:
 * <ul>
 * <li><b>APT mode</b> — the template must compile; use {@code Object} as the sentinel return
 * type and {@code @PermuteReturn} to specify the actual return type</li>
 * <li><b>Custom naming ({@code alpha(j)})</b> — inference requires {@code T${j}} convention;
 * single-letter names do not trigger it</li>
 * <li><b>Non-linear offset</b> — inference assumes {@code i+1}; use explicit for other offsets</li>
 * <li><b>Mixed fixed+growing type args</b> — use {@code typeArgs} with {@code typeArgList()}</li>
 * <li><b>Override boundary omission</b> — use {@code when="true"} to force generation even
 * when the evaluated class name is not in the generated set</li>
 * </ul>
 *
 * <p>
 * <b>Boundary omission:</b> by default, when the evaluated {@code className} is not in the
 * set of class names generated by {@code @Permute} in the current template, the method is
 * silently omitted from that generated class — exactly mirroring the hand-written pattern
 * where the last class in a chain has no {@code join()} method.
 *
 * <p>
 * APT mode example:
 *
 * <pre>
 * {
 *     &#64;code
 *     &#64;Permute(varName = "i", from = "1", to = "4", className = "Step${i}")
 *     public class Step1<T1> {
 *         @PermuteReturn(className = "Step${i+1}", typeArgVarName = "j", typeArgFrom = "1", typeArgTo = "${i+1}", typeArgName = "T${j}")
 *         public Object join(@PermuteDeclr(type = "Source<T${i+1}>") Object src) {
 *             return null;
 *         }
 *     }
 *     // Step4.join() is omitted — Step5 is not in the generated set
 * }
 * </pre>
 */
@Retention(RetentionPolicy.SOURCE)
@Target(ElementType.METHOD)
public @interface PermuteReturn {

    /**
     * Template expression for the return type. Typically a class name
     * (e.g., {@code "Step${i+1}"}), but may also be a type variable name
     * (e.g., {@code "${alpha(i)}"} to return the i-th type parameter).
     * Evaluated against the outer permutation context for each generated class.
     */
    String className();

    /**
     * Variable name for the type argument expansion loop (e.g., {@code "j"}).
     * When empty (the default), no type arguments are generated (raw return type).
     * Mutually exclusive with {@code typeArgs}.
     */
    String typeArgVarName() default "";

    /** Lower bound of the type argument loop. Default {@code "1"}. */
    String typeArgFrom() default "1";

    /**
     * Upper bound of the type argument loop (e.g., {@code "${i+1}"}).
     * Required when {@code typeArgVarName} is set.
     */
    String typeArgTo() default "";

    /** Type argument name template per loop value (e.g., {@code "T${j}"}). */
    String typeArgName() default "";

    /**
     * Full type argument list as a JEXL expression (e.g.,
     * {@code "DS, ${typeArgList(1, i, 'T')}"}). Use when type args are a mix
     * of fixed and growing values. Overrides the {@code typeArgVarName} loop.
     * Mutually exclusive with {@code typeArgVarName}.
     */
    String typeArgs() default "";

    /**
     * Optional JEXL guard expression. When empty (default), boundary omission
     * applies: the method is omitted when the evaluated {@code className} is not
     * in the generated set. Set to {@code "true"} to force generation regardless.
     */
    String when() default "";
}
