package io.quarkiverse.permuplate;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Declares an additional integer loop variable for use inside
 * {@link Permute#extraVars()}. Each {@code @PermuteVar} adds one axis to the
 * cross-product generated by {@code @Permute}.
 *
 * <p>
 * {@code @Target({})} means this annotation may only appear as an element value
 * inside {@code @Permute extraVars} — it cannot be placed directly on any
 * program element.
 *
 * <p>
 * The {@code from} and {@code to} attributes support the same JEXL expression strings
 * and external property sources as {@link Permute#from()} and {@link Permute#to()}.
 * The outer permutation variable (e.g. {@code i}) is available in expressions, so
 * {@code to = "${i}"} is valid.
 *
 * <p>
 * Example:
 *
 * <pre>{@code
 * &#64;Permute(varName = "i", from = "2", to = "4",
 *          className = "Matrix${i}x${k}",
 *          extraVars = { @PermuteVar(varName = "k", from = "2", to = "4") })
 * public class Matrix2x2 { ... }
 * }</pre>
 *
 * Generates {@code Matrix2x2} through {@code Matrix4x4} (9 classes total).
 */
@Retention(RetentionPolicy.SOURCE)
@Target({})
public @interface PermuteVar {
    /** The variable name, referenced as {@code ${varName}} in expressions. */
    String varName();

    /**
     * Inclusive lower bound as a JEXL expression string (e.g. {@code "2"} or
     * {@code "${start}"}). The outer variable and all named constants from
     * {@code @Permute.strings} are available.
     *
     * <p>
     * System properties ({@code -Dpermuplate.*}) and APT options
     * ({@code -Apermuplate.*}) are also available — same resolution order as
     * {@link Permute#from()}.
     *
     * <p>
     * Omit (or leave as {@code ""}) when {@link #values()} is used instead.
     */
    String from() default "";

    /**
     * Inclusive upper bound as a JEXL expression string. Must evaluate to a value
     * &gt;= {@code from}. The outer variable (e.g. {@code i}) is available, enabling
     * patterns like {@code to = "${i}"}.
     *
     * <p>
     * System properties ({@code -Dpermuplate.*}) and APT options
     * ({@code -Apermuplate.*}) are also available — same resolution order as
     * {@link Permute#to()}.
     *
     * <p>
     * Omit (or leave as {@code ""}) when {@link #values()} is used instead.
     */
    String to() default "";

    /**
     * String values to iterate over instead of an integer range.
     * Mutually exclusive with {@link #from()} and {@link #to()}.
     *
     * <p>
     * Example:
     *
     * <pre>{@code
     * &#64;Permute(varName = "i", from = "2", to = "4",
     *          className = "Matrix${i}x${k}",
     *          extraVars = { @PermuteVar(varName = "k", values = {"A","B","C"}) })
     * }</pre>
     *
     * <p>
     * The APT processor reports a compile error if both {@code values} and
     * {@code from}/{@code to} are specified, or if {@code values} is empty.
     */
    String[] values() default {};
}
