package io.quarkiverse.permuplate;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Declares an additional integer loop variable for use inside
 * {@link Permute#extraVars()}. Each {@code @PermuteVar} adds one axis to the
 * cross-product generated by {@code @Permute}.
 *
 * <p>
 * {@code @Target({})} means this annotation may only appear as an element value
 * inside {@code @Permute extraVars} — it cannot be placed directly on any
 * program element.
 *
 * <p>
 * Example:
 *
 * <pre>{@code
 * &#64;Permute(varName = "i", from = 2, to = 4,
 *          className = "Matrix${i}x${k}",
 *          extraVars = { @PermuteVar(varName = "k", from = 2, to = 4) })
 * public class Matrix2x2 { ... }
 * }</pre>
 *
 * Generates {@code Matrix2x2} through {@code Matrix4x4} (9 classes total).
 */
@Retention(RetentionPolicy.SOURCE)
@Target({})
public @interface PermuteVar {
    /** The variable name, referenced as {@code ${varName}} in expressions. */
    String varName();

    /** Inclusive lower bound. */
    int from();

    /** Inclusive upper bound. Must be &gt;= {@code from}. */
    int to();
}
