package io.quarkiverse.permuplate.intellij.safedelete;

import com.intellij.openapi.module.Module;
import com.intellij.openapi.project.Project;
import com.intellij.psi.*;
import com.intellij.refactoring.safeDelete.NonCodeUsageSearchInfo;
import com.intellij.refactoring.safeDelete.SafeDeleteProcessorDelegateBase;
import com.intellij.usageView.UsageInfo;
import io.quarkiverse.permuplate.intellij.index.PermuteFileDetector;
import io.quarkiverse.permuplate.intellij.index.PermuteTemplateData;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.Collection;
import java.util.Collections;
import java.util.List;

/**
 * Safe delete handling for Permuplate classes:
 * - Generated class: blocked via a conflict message explaining it will be recreated.
 * - Template class: warns about the generated family in the conflicts panel.
 *
 * Extends {@link SafeDeleteProcessorDelegateBase} to avoid implementing the deprecated
 * no-Module overload of {@code getElementsToSearch}.
 */
public class PermuteSafeDeleteDelegate extends SafeDeleteProcessorDelegateBase {

    @Override
    public boolean handlesElement(PsiElement element) {
        if (!(element instanceof PsiClass cls)) return false;
        return PermuteFileDetector.isTemplate(cls) || PermuteFileDetector.isGenerated(cls);
    }

    @Override
    public @Nullable NonCodeUsageSearchInfo findUsages(
            @NotNull PsiElement element,
            PsiElement[] allElementsToDelete,
            @NotNull List<? super UsageInfo> result) {
        return null;
    }

    @Override
    public @Nullable Collection<? extends PsiElement> getElementsToSearch(
            @NotNull PsiElement element,
            @Nullable Module module,
            @NotNull Collection<? extends PsiElement> allElementsToDelete) {
        return Collections.emptyList();
    }

    @Override
    public @Nullable Collection<PsiElement> getAdditionalElementsToDelete(
            @NotNull PsiElement element,
            @NotNull Collection<? extends PsiElement> allElementsToDelete,
            boolean askUser) {
        return null;
    }

    /**
     * For generated classes: returns a conflict message that blocks deletion and explains
     * the class will be recreated by the build.
     * For template classes: returns a warning listing the generated family members that
     * will no longer be built.
     */
    @Override
    public Collection<String> findConflicts(
            @NotNull PsiElement element,
            PsiElement[] allElementsToDelete) {
        if (!(element instanceof PsiClass cls)) return Collections.emptyList();
        Project project = cls.getProject();

        if (PermuteFileDetector.isGenerated(cls)) {
            String generatedName = cls.getName() != null ? cls.getName() : "This class";
            String templateName = cls.getName() != null
                    ? PermuteFileDetector.templateNameFor(cls.getName(), project) : null;
            String templateDisplay = templateName != null ? templateName + ".java" : "the template";

            return List.of(
                    "<b>" + generatedName + "</b> is generated by Permuplate from <b>"
                    + templateDisplay + "</b> and will be recreated on the next build. "
                    + "To remove it permanently, delete the template <b>" + templateDisplay + "</b> instead."
            );
        }

        if (PermuteFileDetector.isTemplate(cls)) {
            String templateName = cls.getName() != null ? cls.getName() : "this template";
            PermuteTemplateData data = cls.getName() != null
                    ? PermuteFileDetector.templateDataFor(cls.getName(), project) : null;

            if (data != null && !data.generatedNames.isEmpty()) {
                String generatedList = String.join(", ", data.generatedNames);
                return List.of(
                        "Deleting the Permuplate template <b>" + templateName + "</b> will stop "
                        + "regeneration of: " + generatedList + ". "
                        + "These generated files will remain until cleaned manually."
                );
            }
        }

        return Collections.emptyList();
    }

    @Override
    public UsageInfo[] preprocessUsages(@NotNull Project project, UsageInfo[] usages) {
        return usages;
    }

    @Override
    public void prepareForDeletion(@NotNull PsiElement element)
            throws com.intellij.util.IncorrectOperationException {}

    @Override
    public boolean isToSearchInComments(@NotNull PsiElement element) { return false; }

    @Override
    public void setToSearchInComments(@NotNull PsiElement element, boolean enabled) {}

    @Override
    public boolean isToSearchForTextOccurrences(@NotNull PsiElement element) { return false; }

    @Override
    public void setToSearchForTextOccurrences(@NotNull PsiElement element, boolean enabled) {}
}
