package io.quarkiverse.permuplate.intellij.rename;

import com.intellij.openapi.actionSystem.CommonDataKeys;
import com.intellij.openapi.actionSystem.DataContext;
import com.intellij.openapi.application.ReadAction;
import com.intellij.openapi.editor.Editor;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.Messages;
import com.intellij.openapi.vfs.LocalFileSystem;
import com.intellij.openapi.vfs.VirtualFile;
import com.intellij.psi.*;
import com.intellij.refactoring.rename.RenameHandler;
import io.quarkiverse.permuplate.intellij.index.PermuteFileDetector;
import io.quarkiverse.permuplate.intellij.index.PermuteTemplateData;
import org.jetbrains.annotations.NotNull;

/**
 * Intercepts rename actions inside generated files and redirects the user
 * to the template. Registered with order="first" to run before IntelliJ's
 * default rename handler.
 */
public class GeneratedFileRenameHandler implements RenameHandler {

    @Override
    public boolean isAvailableOnDataContext(@NotNull DataContext dataContext) {
        VirtualFile file = CommonDataKeys.VIRTUAL_FILE.getData(dataContext);
        if (file == null || !PermuteFileDetector.isGeneratedFile(file)) return false;
        // Permuplate-managed generated files are handled silently by
        // AnnotationStringRenameProcessor.substituteElementToRename() — no block dialog needed.
        Project project = CommonDataKeys.PROJECT.getData(dataContext);
        if (project != null && isPermuteManagedFile(project, file)) return false;
        return true;
    }

    private static boolean isPermuteManagedFile(@NotNull Project project, @NotNull VirtualFile file) {
        return ReadAction.compute(() -> {
            PsiFile psiFile = PsiManager.getInstance(project).findFile(file);
            if (!(psiFile instanceof PsiJavaFile javaFile)) return false;
            PsiClass[] classes = javaFile.getClasses();
            if (classes.length == 0) return false;
            String className = classes[0].getName();
            return className != null && PermuteFileDetector.templateNameFor(className, project) != null;
        });
    }

    @Override
    public void invoke(@NotNull Project project, Editor editor,
                       PsiFile file, @NotNull DataContext dataContext) {
        showRedirectDialog(project, file);
    }

    @Override
    public void invoke(@NotNull Project project, @NotNull PsiElement[] elements,
                       @NotNull DataContext dataContext) {
        Project p = CommonDataKeys.PROJECT.getData(dataContext);
        if (p == null) return;
        PsiFile file = elements.length > 0 ? elements[0].getContainingFile() : null;
        showRedirectDialog(p, file);
    }

    private static void showRedirectDialog(@NotNull Project project, PsiFile generatedFile) {
        String generatedName = generatedFile != null ? generatedFile.getName() : "this file";
        String templateDisplay = resolveTemplateName(project, generatedFile);

        String message = "<html><b>" + generatedName + "</b> is generated by Permuplate from <b>"
                + templateDisplay + "</b>.<br>" +
                "Edits will be overwritten on the next build.<br><br>" +
                "To rename this element, rename it in the template instead.</html>";

        int choice = Messages.showDialog(
                project,
                message,
                "Generated File — Rename Blocked",
                new String[]{"Go to Template", "Cancel"},
                0,
                Messages.getWarningIcon());

        if (choice == 0) {
            navigateToTemplate(project, generatedFile);
        }
    }

    private static String resolveTemplateName(@NotNull Project project, PsiFile generatedFile) {
        if (!(generatedFile instanceof PsiJavaFile)) return "the template";
        PsiJavaFile jf = (PsiJavaFile) generatedFile;
        PsiClass[] classes = jf.getClasses();
        if (classes.length == 0) return "the template";
        String className = classes[0].getName();
        if (className == null) return "the template";
        String templateName = PermuteFileDetector.templateNameFor(className, project);
        return templateName != null ? templateName + ".java" : "the template";
    }

    private static void navigateToTemplate(@NotNull Project project, PsiFile generatedFile) {
        if (!(generatedFile instanceof PsiJavaFile)) return;
        PsiJavaFile jf = (PsiJavaFile) generatedFile;
        PsiClass[] classes = jf.getClasses();
        if (classes.length == 0) return;
        String className = classes[0].getName();
        if (className == null) return;

        String templateName = PermuteFileDetector.templateNameFor(className, project);
        if (templateName == null) return;

        PermuteTemplateData data = PermuteFileDetector.templateDataFor(templateName, project);
        if (data == null) return;

        VirtualFile templateVFile = LocalFileSystem.getInstance()
                .findFileByPath(data.templateFilePath);
        if (templateVFile == null) return;

        PsiFile templatePsiFile = PsiManager.getInstance(project).findFile(templateVFile);
        if (templatePsiFile instanceof com.intellij.pom.Navigatable) {
            com.intellij.pom.Navigatable nav = (com.intellij.pom.Navigatable) templatePsiFile;
            nav.navigate(true);
        }
    }
}
