package io.quarkiverse.permuplate.processor;

import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.AnnotationValue;
import javax.lang.model.element.Element;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.PackageElement;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;

import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.Modifier;
import com.github.javaparser.ast.NodeList;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.EnumDeclaration;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.body.RecordDeclaration;
import com.github.javaparser.ast.body.TypeDeclaration;
import com.github.javaparser.ast.expr.MemberValuePair;
import com.github.javaparser.ast.expr.NormalAnnotationExpr;
import com.sun.source.util.TreePath;
import com.sun.source.util.Trees;

import io.quarkiverse.permuplate.Permute;
import io.quarkiverse.permuplate.PermuteVar;
import io.quarkiverse.permuplate.core.EvaluationContext;
import io.quarkiverse.permuplate.core.PermuteConfig;
import io.quarkiverse.permuplate.core.PermuteDeclrTransformer;
import io.quarkiverse.permuplate.core.PermuteParamTransformer;
import io.quarkiverse.permuplate.core.PermuteStatementsTransformer;
import io.quarkiverse.permuplate.core.PermuteTypeParamTransformer;
import io.quarkiverse.permuplate.core.PermuteValueTransformer;
import io.quarkiverse.permuplate.ide.AnnotationStringAlgorithm;
import io.quarkiverse.permuplate.ide.AnnotationStringTemplate;

/**
 * Annotation processor for {@link Permute}.
 *
 * <p>
 * {@code @Permute} is supported in two positions:
 *
 * <ul>
 * <li><b>On a class or interface</b> — for each combination of permutation
 * variables, clones the type declaration, applies all transformations, and writes
 * a new top-level source file. With {@code extraVars}, generates one file per
 * cross-product combination.</li>
 * <li><b>On a method</b> — for each combination, clones and transforms the method,
 * then collects all variants into a single new class containing N overloads.</li>
 * </ul>
 *
 * <p>
 * Transformation order for each permutation:
 * <ol>
 * <li>Type/method rename</li>
 * <li>{@code @PermuteDeclr} on fields — rename declaration + propagate to whole class</li>
 * <li>{@code @PermuteDeclr} on constructor parameters — rename + propagate in constructor body</li>
 * <li>{@code @PermuteDeclr} on for-each / local variables — rename + propagate in enclosing scope</li>
 * <li>{@code @PermuteParam} — replace parameter list + expand anchor at call sites</li>
 * <li>Strip all permgen imports and leftover annotations</li>
 * </ol>
 */
@SupportedAnnotationTypes("io.quarkiverse.permuplate.Permute")
@SupportedSourceVersion(SourceVersion.RELEASE_17)
public class PermuteProcessor extends AbstractProcessor {

    private Trees trees;

    /** All class names generated by ALL @Permute templates in the current round. Built once per round in process(). */
    private Set<String> globalGeneratedNames = new java.util.HashSet<>();

    /**
     * External properties injected into JEXL contexts for evaluating {@code from}/{@code to}.
     * Built once per round from APT options ({@code -Apermuplate.*}) and system properties
     * ({@code -Dpermuplate.*}), with APT options taking priority over system properties.
     */
    private java.util.Map<String, Object> externalProperties = java.util.Collections.emptyMap();

    @Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        // Enable Java 17 syntax (records, sealed classes) in JavaParser
        com.github.javaparser.StaticJavaParser.getParserConfiguration()
                .setLanguageLevel(com.github.javaparser.ParserConfiguration.LanguageLevel.JAVA_17);
        super.init(processingEnv);
        try {
            trees = Trees.instance(processingEnv);
        } catch (Exception e) {
            processingEnv.getMessager().printMessage(
                    Diagnostic.Kind.NOTE, "Trees.instance() failed: " + e.getMessage());
        }
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (roundEnv.processingOver())
            return false;

        TypeElement permuteAnnotationType = processingEnv.getElementUtils()
                .getTypeElement("io.quarkiverse.permuplate.Permute");
        if (permuteAnnotationType == null) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE,
                    "PermuteProcessor: could not find Permute annotation type");
            return false;
        }

        Set<? extends Element> annotated = roundEnv.getElementsAnnotatedWith(permuteAnnotationType);
        processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE,
                "PermuteProcessor: found " + annotated.size() + " @Permute-annotated elements");

        // Build external properties for this round: APT options (-Apermuplate.*) take
        // priority over system properties (-Dpermuplate.*). Both have "permuplate." stripped.
        externalProperties = PermuteConfig.buildExternalProperties(
                new java.util.HashMap<>(processingEnv.getOptions()), true);

        // Build global generated-names set across all @Permute templates in this round.
        // Used by implicit return type inference (applyPermuteReturn) to find cross-template
        // generated class names for boundary omission decisions.
        // Filters are applied here so that filtered-out classes are absent from the set —
        // otherwise @PermuteReturn boundary omission would not omit methods that reference
        // a class that @PermuteFilter has removed from generation.
        globalGeneratedNames = new java.util.HashSet<>();
        for (Element elem : annotated) {
            if (elem instanceof TypeElement) {
                Permute p = ((TypeElement) elem).getAnnotation(Permute.class);
                if (p != null) {
                    try {
                        List<String> elemFilterExprs = readFilterExpressions(elem);
                        globalGeneratedNames.addAll(buildGeneratedSet(p, elem, elemFilterExprs));
                    } catch (Exception ignored) {
                        // If generation fails during global set building (e.g. malformed strings),
                        // skip it — the proper error will be reported in processTypePermutation
                    }
                }
            }
        }

        for (Element element : annotated) {
            if (element instanceof TypeElement) {
                processTypePermutation((TypeElement) element);
            } else if (element instanceof ExecutableElement) {
                processMethodPermutation((ExecutableElement) element);
            }
        }
        return true;
    }

    // -------------------------------------------------------------------------
    // Type permutation — generates one file per variable combination
    // -------------------------------------------------------------------------

    private void processTypePermutation(TypeElement typeElement) {
        Permute permute = typeElement.getAnnotation(Permute.class);
        AnnotationMirror permuteMirror = findAnnotationMirror(typeElement, "io.quarkiverse.permuplate.Permute");

        // --- values XOR from/to validation ---
        String[] values = permute.values();
        boolean hasValues = values.length > 0;
        boolean hasFrom = !permute.from().isEmpty();
        boolean hasTo = !permute.to().isEmpty();

        AnnotationValue valuesAttr = findAnnotationValue(permuteMirror, "values");
        boolean valuesExplicit = valuesAttr != null; // true only if user wrote values={...}

        // Case 1: values explicitly provided but empty
        if (valuesExplicit && !hasValues) {
            error("@Permute 'values' must not be empty — provide at least one string",
                    typeElement, permuteMirror, valuesAttr);
            return;
        }

        // Case 2: values + from/to both specified
        if (hasValues && (hasFrom || hasTo)) {
            error("@Permute 'values' and 'from'/'to' are mutually exclusive — use one or the other",
                    typeElement, permuteMirror, valuesAttr);
            return;
        }

        // Case 3: neither values nor from/to
        if (!hasValues && (!hasFrom || !hasTo)) {
            AnnotationValue fromAttr = findAnnotationValue(permuteMirror, "from");
            error("@Permute requires either 'values' (non-empty) or both 'from' and 'to' — "
                    + "specify values={...} for a string set or from=\"N\", to=\"M\" for an integer range",
                    typeElement, permuteMirror, fromAttr);
            return;
        }

        // Build PermuteConfig now that mode is determined
        PermuteConfig permuteConfig = PermuteConfig.from(permute);

        // Integer-mode only: validate from <= to
        if (!hasValues) {
            EvaluationContext baseCtx = new EvaluationContext(
                    PermuteConfig.buildBaseVars(permuteConfig, externalProperties));
            int fromVal, toVal;
            try {
                fromVal = baseCtx.evaluateInt(permute.from());
                toVal = baseCtx.evaluateInt(permute.to());
            } catch (Exception e) {
                error("@Permute from/to expression failed to evaluate: " + e.getMessage(),
                        typeElement, permuteMirror, findAnnotationValue(permuteMirror, "from"));
                return;
            }
            if (fromVal > toVal) {
                error(String.format(
                        "@Permute has invalid range: from=%d is greater than to=%d — no classes will be generated",
                        fromVal, toVal),
                        typeElement, permuteMirror, findAnnotationValue(permuteMirror, "from"));
                return;
            }
        }

        // @PermuteSource is only valid in Maven plugin mode
        boolean hasPermuteSource = processingEnv.getElementUtils()
                .getAllAnnotationMirrors(typeElement).stream()
                .anyMatch(m -> {
                    String fqn = ((javax.lang.model.element.TypeElement) m.getAnnotationType().asElement()).getQualifiedName()
                            .toString();
                    return "io.quarkiverse.permuplate.PermuteSource".equals(fqn)
                            || "io.quarkiverse.permuplate.PermuteSources".equals(fqn);
                });
        if (hasPermuteSource) {
            AnnotationMirror sourceMirror = findAnnotationMirror(typeElement,
                    "io.quarkiverse.permuplate.PermuteSource");
            if (sourceMirror == null) {
                sourceMirror = findAnnotationMirror(typeElement,
                        "io.quarkiverse.permuplate.PermuteSources");
            }
            error("@PermuteSource requires the Maven plugin (permuplate-maven-plugin). "
                    + "Use inline=true with the Maven plugin instead of APT.",
                    typeElement, sourceMirror, null);
            return;
        }

        // Check for inline — APT cannot generate inline (requires Maven plugin)
        if (permute.inline()) {
            boolean isNested = typeElement.getEnclosingElement() instanceof TypeElement;
            if (!isNested) {
                error("@Permute inline = true is only valid on nested static classes — " +
                        "there is no parent class to inline into",
                        typeElement, permuteMirror, findAnnotationValue(permuteMirror, "inline"));
            } else {
                error("@Permute inline = true requires permuplate-maven-plugin — " +
                        "the annotation processor cannot modify existing source files. " +
                        "See README §'APT vs Maven Plugin' for migration instructions.",
                        typeElement, permuteMirror, findAnnotationValue(permuteMirror, "inline"));
            }
            return;
        }

        // In APT mode, keepTemplate=true has no effect when inline=false — the template
        // class is already in src/main/java/ and compiled normally. In Maven plugin mode
        // (src/main/permuplate/), keepTemplate=true causes the template class to be written
        // to the generated sources directory so it is compiled alongside the generated classes.
        if (permute.keepTemplate() && !permute.inline()) {
            processingEnv.getMessager().printMessage(
                    Diagnostic.Kind.WARNING,
                    "@Permute keepTemplate = true has no effect in APT mode when inline = false"
                            + " — the template class is already compiled from its source location."
                            + " To use keepTemplate = true with inline = false, use the Maven plugin"
                            + " (place the template in src/main/permuplate/).",
                    typeElement, permuteMirror, findAnnotationValue(permuteMirror, "keepTemplate"));
        }

        if (!validateStrings(permute, typeElement, permuteMirror))
            return;

        if (!validateExtraVars(permute, typeElement, permuteMirror))
            return;

        // R1: className must contain at least one ${...} variable
        if (!permute.className().contains("${")) {
            error(String.format(
                    "@Permute className \"%s\" contains no variables — every permutation will" +
                            " produce the same class name; add a ${%s} expression",
                    permute.className(), permute.varName()),
                    typeElement, permuteMirror, findAnnotationValue(permuteMirror, "className"));
            return;
        }

        // R1b: every extraVars variable must appear somewhere in className
        String classNameTemplate = permute.className();
        List<String> missingVars = new ArrayList<>();
        for (PermuteVar extra : permute.extraVars()) {
            if (!classNameTemplate.contains("${" + extra.varName() + "}")) {
                missingVars.add(extra.varName());
            }
        }
        if (!missingVars.isEmpty()) {
            for (String missing : missingVars) {
                error(String.format(
                        "@Permute className \"%s\" never uses extraVars variable \"%s\" —" +
                                " every value of %s generates the same class name, producing" +
                                " duplicates; add ${%s} to className",
                        permute.className(), missing, missing, missing),
                        typeElement, permuteMirror, findAnnotationValue(permuteMirror, "extraVars"));
            }
            return;
        }

        // R2 for className: all static literals must appear as substrings of the template class name
        String templateSimpleName = typeElement.getSimpleName().toString();
        {
            AnnotationStringTemplate parsedClassNameTemplate = AnnotationStringAlgorithm.parse(permute.className());
            if (!parsedClassNameTemplate.hasNoLiteral()
                    && !AnnotationStringAlgorithm.matches(parsedClassNameTemplate, templateSimpleName)) {
                error(String.format(
                        "@Permute className \"%s\" has a literal that does not appear as a" +
                                " substring of the template class name \"%s\" —" +
                                " the className expression must reference the template class name",
                        permute.className(), templateSimpleName),
                        typeElement, permuteMirror, findAnnotationValue(permuteMirror, "className"));
                return;
            }
        }

        CompilationUnit templateCu = parseSource(typeElement);
        if (templateCu == null)
            return;

        Optional<TypeDeclaration<?>> foundForValidation = findTemplateType(templateCu, templateSimpleName);
        // Skip all @PermuteDeclr and @PermuteParam prefix validation in string-set mode.
        // R4 (no-anchor) fires spuriously for pure-variable expressions like "${T}" where
        // the variable substitutes the entire type name with no literal prefix.
        // R2 (unmatched literal) and R3 (orphan variable) are also skipped as a consequence —
        // a reasonable trade-off since string-typed variables have no integer anchor.
        if (!hasValues && foundForValidation.isPresent()) {
            TypeDeclaration<?> templateClassDecl = foundForValidation.get();
            Map<String, String> stringConstants = buildStringConstants(permute);
            boolean declrValid = PermuteDeclrTransformer.validatePrefixes(
                    templateClassDecl, processingEnv.getMessager(), typeElement, stringConstants);
            boolean paramValid = PermuteParamTransformer.validatePrefixes(
                    templateClassDecl, processingEnv.getMessager(), typeElement, stringConstants);
            if (!declrValid || !paramValid)
                return;
        }

        // Read filter expressions before building the generated set so that filtered-out
        // classes are absent from the set used by @PermuteReturn boundary omission.
        List<String> filterExprs = readFilterExpressions(typeElement);
        // Build generated set once for boundary omission in @PermuteReturn
        Set<String> generatedSet = buildGeneratedSet(permute, typeElement, filterExprs);
        List<Map<String, Object>> allCombinations = PermuteConfig.buildAllCombinations(permuteConfig, externalProperties);
        List<Map<String, Object>> filteredCombinations = applyFilters(allCombinations, filterExprs, typeElement);

        if (filteredCombinations.isEmpty()) {
            AnnotationMirror filterMirror = findAnnotationMirror(typeElement,
                    "io.quarkiverse.permuplate.PermuteFilter");
            if (filterMirror == null) {
                filterMirror = findAnnotationMirror(typeElement,
                        "io.quarkiverse.permuplate.PermuteFilters");
            }
            error("@PermuteFilter eliminates all permutations in the range "
                    + permuteConfig.from + ".." + permuteConfig.to
                    + " — at least one combination must pass",
                    typeElement, filterMirror, null);
            return;
        }

        for (Map<String, Object> vars : filteredCombinations) {
            generatePermutation(templateCu, typeElement, permute, new EvaluationContext(vars), generatedSet);
        }
    }

    /**
     * Computes the set of class names that this @Permute annotation will actually generate,
     * after applying any @PermuteFilter expressions. Filtered-out combinations are excluded
     * so that @PermuteReturn boundary omission treats them as non-existent.
     */
    private Set<String> buildGeneratedSet(Permute permute, Element element, List<String> filterExprs) {
        Set<String> names = new HashSet<>();
        List<Map<String, Object>> combinations = PermuteConfig.buildAllCombinations(PermuteConfig.from(permute),
                externalProperties);
        if (!filterExprs.isEmpty()) {
            combinations = applyFilters(combinations, filterExprs, element);
        }
        for (Map<String, Object> vars : combinations) {
            try {
                names.add(new EvaluationContext(vars).evaluate(permute.className()));
            } catch (Exception ignored) {
            }
        }
        return names;
    }

    private void generatePermutation(CompilationUnit templateCu, TypeElement typeElement,
            Permute permute, EvaluationContext ctx, Set<String> generatedSet) {
        String templateClassName = typeElement.getSimpleName().toString();
        AnnotationMirror permuteMirror = findAnnotationMirror(typeElement, "io.quarkiverse.permuplate.Permute");

        // Find the type (class, interface, or record) by name anywhere in the compilation unit
        Optional<TypeDeclaration<?>> found = findTemplateType(templateCu, templateClassName);
        if (!found.isPresent()) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                    "Cannot find class " + templateClassName + " in source", typeElement);
            return;
        }

        // Clone just the type declaration — handles both top-level and nested types.
        TypeDeclaration<?> classDecl = (TypeDeclaration<?>) found.get().clone();

        // If the template was a nested type, strip modifiers that don't apply to top-level.
        // removeModifier is on Node/TypeDeclaration so it works for both classes and records.
        classDecl.removeModifier(Modifier.Keyword.STATIC);
        if (!classDecl.isPublic()) {
            classDecl.setModifier(Modifier.Keyword.PUBLIC, true);
        }

        // 1. Rename the class/record
        String newClassName;
        try {
            newClassName = ctx.evaluate(permute.className());
        } catch (Exception e) {
            error("Failed to evaluate @Permute className \"" + permute.className() + "\": " + e.getMessage(),
                    typeElement, permuteMirror, findAnnotationValue(permuteMirror, "className"));
            return;
        }
        if (newClassName == null || newClassName.isBlank()) {
            error("@Permute className \"" + permute.className() + "\" evaluated to an empty name",
                    typeElement, permuteMirror, findAnnotationValue(permuteMirror, "className"));
            return;
        }
        classDecl.setName(newClassName);
        // Constructor names must match the class name — rename them all to match.
        // JavaParser does not propagate class renames to constructors automatically.
        // getConstructors() is on TypeDeclaration<?> — works for both classes and records.
        classDecl.getConstructors().forEach(ctor -> ctor.setName(newClassName));

        // 1b. Expand class type parameters (@PermuteTypeParam — explicit and implicit)
        // Note: @PermuteTypeParam is on TypeParameters (not the class annotation list).
        // The transformer replaces each sentinel TypeParameter with j expanded TypeParameters
        // that carry no annotations — so @PermuteTypeParam disappears by construction.
        // Pass globalGeneratedNames so R1 validation skips methods that implicit inference
        // will handle later (step 5d).
        PermuteTypeParamTransformer.transform(classDecl, ctx,
                processingEnv.getMessager(), typeElement, globalGeneratedNames);

        // 1c. Extends clause expansion — only applies to classes/interfaces, not records.
        // Must run after @PermuteTypeParam so postG1TypeParams reflects the expanded list.
        if (classDecl instanceof ClassOrInterfaceDeclaration coid) {
            java.util.List<String> postG1TypeParams = coid.getTypeParameters().stream()
                    .map(tp -> tp.getNameAsString())
                    .collect(java.util.stream.Collectors.toList());
            int templateEmbeddedNum = firstEmbeddedNumber(templateClassName);
            int currentEmbeddedNum = firstEmbeddedNumber(newClassName);
            applyExtendsExpansion(coid, templateClassName, templateEmbeddedNum,
                    currentEmbeddedNum, postG1TypeParams);
        }

        // 2, 3 & 4. @PermuteDeclr — fields, constructor params, then for-each vars
        PermuteDeclrTransformer.transform(classDecl, ctx, processingEnv.getMessager());

        // 5. @PermuteParam — expand parameter list + anchor expansion at call sites
        PermuteParamTransformer.transform(classDecl, ctx, processingEnv.getMessager());

        // Note: @PermuteTypeParam annotations on TypeParameters are NOT in classDecl.getAnnotations()
        // (which only contains class-level annotations). The PermuteTypeParamTransformer in step 1b
        // replaces the sentinel TypeParameter with freshly constructed TypeParameters that carry
        // no annotations — so @PermuteTypeParam disappears by construction. No explicit removal needed.

        // 5b. @PermuteMethod — generate overloads with explicit @PermuteReturn
        // Only applies to class/interface declarations (records don't support arbitrary methods).
        if (classDecl instanceof ClassOrInterfaceDeclaration coid) {
            applyPermuteMethodApt(coid, ctx, permute, typeElement);
        } else {
            // For records and enums: @PermuteMethod is not processed, but the annotation must be
            // stripped from the generated output — the permuplate import is removed from the CU,
            // so any surviving @PermuteMethod reference would fail to compile.
            classDecl.getMethods().forEach(m -> m.getAnnotations().removeIf(a -> {
                String n = a.getNameAsString();
                return n.equals("PermuteMethod") || n.equals("io.quarkiverse.permuplate.PermuteMethod");
            }));
        }

        // 5c. @PermuteReturn — replace Object sentinel return type + boundary omission.
        // Collect explicit-return method keys BEFORE applyPermuteReturn removes annotations,
        // so that step 5d can exclude them from implicit inference.
        // Only applies to class/interface declarations.
        if (classDecl instanceof ClassOrInterfaceDeclaration coid) {
            java.util.Set<String> explicitReturnMethods = collectExplicitReturnMethods(coid);
            applyPermuteReturn(coid, ctx, generatedSet, typeElement);

            // 5d. Implicit return type inference — fires on methods with T+number growing tips
            // that have no explicit @PermuteReturn. Uses globalGeneratedNames for cross-template
            // boundary omission. Runs AFTER applyPermuteReturn so explicit return types are already set.
            applyImplicitInference(coid, globalGeneratedNames, explicitReturnMethods);
        }

        // 5e. @PermuteCase — expand switch statement cases per permutation
        io.quarkiverse.permuplate.core.PermuteCaseTransformer.transform(classDecl, ctx);

        // 5f. @PermuteValue — replace field initializers and method statement RHS (before insertions)
        PermuteValueTransformer.transform(classDecl, ctx);

        // 5g. @PermuteStatements — insert accumulated statements into method bodies
        PermuteStatementsTransformer.transform(classDecl, ctx);

        // 5g2. @PermuteBody — replace entire method or constructor body per permutation
        io.quarkiverse.permuplate.core.PermuteBodyTransformer.transform(classDecl, ctx);

        // 5g3. @PermuteEnumConst — expand sentinel enum constants (no-op for non-enum types)
        io.quarkiverse.permuplate.core.PermuteEnumConstTransformer.transform(classDecl, ctx);

        // 5h. @PermuteAnnotation — add Java annotations to generated elements (runs last)
        io.quarkiverse.permuplate.core.PermuteAnnotationTransformer.transform(
                classDecl, ctx, processingEnv.getMessager(), typeElement);

        // 5i. @PermuteThrows — add exception types to method throws clauses
        io.quarkiverse.permuplate.core.PermuteThrowsTransformer.transform(
                classDecl, ctx, processingEnv.getMessager(), typeElement);

        // TODO: extract PermuteFilter/PermuteFilters predicate to a shared constant — used in 3 places
        // 6. Remove @Permute and @PermuteFilter / @PermuteFilters from the class
        classDecl.getAnnotations().removeIf(a -> {
            String name = a.getNameAsString();
            return name.equals("Permute") || name.equals("io.quarkiverse.permuplate.Permute")
                    || name.equals("PermuteFilter") || name.equals("io.quarkiverse.permuplate.PermuteFilter")
                    || name.equals("PermuteFilters") || name.equals("io.quarkiverse.permuplate.PermuteFilters");
        });

        // Build a fresh CompilationUnit, copying package and non-permuplate imports.
        CompilationUnit generatedCu = new CompilationUnit();
        templateCu.getPackageDeclaration().ifPresent(p -> generatedCu.setPackageDeclaration(p.clone()));
        templateCu.getImports().forEach(imp -> {
            if (!imp.getNameAsString().startsWith("io.quarkiverse.permuplate")) {
                generatedCu.addImport(imp.clone());
            }
        });

        // @PermuteImport — add per-permutation evaluated imports to the generated CU
        collectPermuteImports(classDecl).forEach(importStr -> {
            try {
                generatedCu.addImport(ctx.evaluate(importStr));
            } catch (Exception e) {
                error("@PermuteImport expression failed to evaluate: " + e.getMessage(),
                        typeElement, null, null);
            }
        });
        // Strip @PermuteImport / @PermuteImports annotations from the generated class
        classDecl.getAnnotations().removeIf(a -> {
            String n = a.getNameAsString();
            return n.equals("PermuteImport") || n.equals("io.quarkiverse.permuplate.PermuteImport")
                    || n.equals("PermuteImports") || n.equals("io.quarkiverse.permuplate.PermuteImports");
        });

        generatedCu.addType(classDecl);

        writeGeneratedClass(typeElement, newClassName, generatedCu.toString());
    }

    // -------------------------------------------------------------------------
    // Method permutation — generates ONE file containing N method overloads
    // -------------------------------------------------------------------------

    private void processMethodPermutation(ExecutableElement methodElement) {
        TypeElement enclosingClass = (TypeElement) methodElement.getEnclosingElement();
        Permute permute = methodElement.getAnnotation(Permute.class);
        AnnotationMirror permuteMirror = findAnnotationMirror(methodElement, "io.quarkiverse.permuplate.Permute");

        // --- values XOR from/to validation ---
        String[] methodValues = permute.values();
        boolean methodHasValues = methodValues.length > 0;
        boolean methodHasFrom = !permute.from().isEmpty();
        boolean methodHasTo = !permute.to().isEmpty();

        AnnotationValue methodValuesAttr = findAnnotationValue(permuteMirror, "values");
        boolean methodValuesExplicit = methodValuesAttr != null; // true only if user wrote values={...}

        // Case 1: values explicitly provided but empty
        if (methodValuesExplicit && !methodHasValues) {
            error("@Permute 'values' must not be empty — provide at least one string",
                    methodElement, permuteMirror, methodValuesAttr);
            return;
        }

        // Case 2: values + from/to both specified
        if (methodHasValues && (methodHasFrom || methodHasTo)) {
            error("@Permute 'values' and 'from'/'to' are mutually exclusive — use one or the other",
                    methodElement, permuteMirror, methodValuesAttr);
            return;
        }

        // Case 3: neither values nor from/to
        if (!methodHasValues && (!methodHasFrom || !methodHasTo)) {
            AnnotationValue methodFromAttr = findAnnotationValue(permuteMirror, "from");
            error("@Permute requires either 'values' (non-empty) or both 'from' and 'to' — "
                    + "specify values={...} for a string set or from=\"N\", to=\"M\" for an integer range",
                    methodElement, permuteMirror, methodFromAttr);
            return;
        }

        PermuteConfig methodConfig = PermuteConfig.from(permute);

        // Integer-mode only: validate from <= to
        if (!methodHasValues) {
            EvaluationContext methodBaseCtx = new EvaluationContext(
                    PermuteConfig.buildBaseVars(methodConfig, externalProperties));
            int methodFromVal, methodToVal;
            try {
                methodFromVal = methodBaseCtx.evaluateInt(permute.from());
                methodToVal = methodBaseCtx.evaluateInt(permute.to());
            } catch (Exception e) {
                error("@Permute from/to expression failed to evaluate: " + e.getMessage(),
                        methodElement, permuteMirror, findAnnotationValue(permuteMirror, "from"));
                return;
            }
            if (methodFromVal > methodToVal) {
                error(String.format(
                        "@Permute has invalid range: from=%d is greater than to=%d — no methods will be generated",
                        methodFromVal, methodToVal),
                        methodElement, permuteMirror, findAnnotationValue(permuteMirror, "from"));
                return;
            }
        }

        if (!validateStrings(permute, methodElement, permuteMirror))
            return;

        if (!validateExtraVars(permute, methodElement, permuteMirror))
            return;

        CompilationUnit templateCu = parseSource(enclosingClass);
        if (templateCu == null)
            return;

        // Locate the enclosing class in the AST
        String enclosingName = enclosingClass.getSimpleName().toString();
        Optional<ClassOrInterfaceDeclaration> foundClass = templateCu.findFirst(
                ClassOrInterfaceDeclaration.class, c -> c.getNameAsString().equals(enclosingName));
        if (!foundClass.isPresent()) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                    "Cannot find class " + enclosingName + " in source", methodElement);
            return;
        }

        // Locate the annotated method by name and parameter count
        String methodName = methodElement.getSimpleName().toString();
        int methodParamCount = methodElement.getParameters().size();
        Optional<MethodDeclaration> foundMethod = foundClass.get().getMethods().stream()
                .filter(m -> m.getNameAsString().equals(methodName)
                        && m.getParameters().size() == methodParamCount)
                .findFirst();
        if (!foundMethod.isPresent()) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                    "Cannot find method " + methodName + " in class " + enclosingName, methodElement);
            return;
        }

        // Evaluate the output class name using the first combination's context.
        List<Map<String, Object>> allCombinations = PermuteConfig.buildAllCombinations(methodConfig, externalProperties);
        List<String> filterExprsM = readFilterExpressions(methodElement);
        List<Map<String, Object>> filteredCombinations = applyFilters(allCombinations, filterExprsM, methodElement);

        if (filteredCombinations.isEmpty()) {
            AnnotationMirror filterMirror = findAnnotationMirror(methodElement,
                    "io.quarkiverse.permuplate.PermuteFilter");
            if (filterMirror == null) {
                filterMirror = findAnnotationMirror(methodElement,
                        "io.quarkiverse.permuplate.PermuteFilters");
            }
            error("@PermuteFilter eliminates all permutations in the range "
                    + methodConfig.from + ".." + methodConfig.to
                    + " — at least one combination must pass",
                    methodElement, filterMirror, null);
            return;
        }

        EvaluationContext firstCtx = new EvaluationContext(filteredCombinations.get(0));
        String outputClassName;
        try {
            outputClassName = firstCtx.evaluate(permute.className());
        } catch (Exception e) {
            error("Failed to evaluate @Permute className \"" + permute.className() + "\": " + e.getMessage(),
                    methodElement, permuteMirror, findAnnotationValue(permuteMirror, "className"));
            return;
        }
        if (outputClassName == null || outputClassName.isBlank()) {
            error("@Permute className evaluated to an empty name",
                    methodElement, permuteMirror, findAnnotationValue(permuteMirror, "className"));
            return;
        }

        // Generate one method variant per combination.
        List<MethodDeclaration> methods = new ArrayList<>();
        for (Map<String, Object> vars : filteredCombinations) {
            EvaluationContext ctx = new EvaluationContext(vars);
            MethodDeclaration clone = foundMethod.get().clone();

            // Strip @Permute and @PermuteFilter / @PermuteFilters from the clone
            clone.getAnnotations().removeIf(a -> {
                String name = a.getNameAsString();
                return name.equals("Permute") || name.equals("io.quarkiverse.permuplate.Permute")
                        || name.equals("PermuteFilter") || name.equals("io.quarkiverse.permuplate.PermuteFilter")
                        || name.equals("PermuteFilters") || name.equals("io.quarkiverse.permuplate.PermuteFilters");
            });

            // Wrap in a temporary class so the existing transformers can operate normally
            ClassOrInterfaceDeclaration wrapper = new ClassOrInterfaceDeclaration(
                    new NodeList<>(), false, "_W");
            wrapper.addMember(clone);
            PermuteDeclrTransformer.transform(wrapper, ctx, processingEnv.getMessager());
            PermuteParamTransformer.transform(wrapper, ctx, processingEnv.getMessager());
            methods.add(wrapper.getMethods().get(0));
        }

        // Assemble the output class
        ClassOrInterfaceDeclaration generatedClass = foundClass.get().clone();
        generatedClass.setName(outputClassName);
        generatedClass.setStatic(false);
        if (!generatedClass.isPublic()) {
            generatedClass.setModifier(Modifier.Keyword.PUBLIC, true);
        }
        generatedClass.getAnnotations().removeIf(a -> {
            String name = a.getNameAsString();
            return name.equals("Permute") || name.equals("io.quarkiverse.permuplate.Permute")
                    || name.equals("PermuteFilter") || name.equals("io.quarkiverse.permuplate.PermuteFilter")
                    || name.equals("PermuteFilters") || name.equals("io.quarkiverse.permuplate.PermuteFilters");
        });
        generatedClass.setMembers(new NodeList<>());
        for (MethodDeclaration m : methods) {
            generatedClass.addMember(m);
        }

        CompilationUnit generatedCu = new CompilationUnit();
        templateCu.getPackageDeclaration().ifPresent(p -> generatedCu.setPackageDeclaration(p.clone()));
        templateCu.getImports().forEach(imp -> {
            if (!imp.getNameAsString().startsWith("io.quarkiverse.permuplate")) {
                generatedCu.addImport(imp.clone());
            }
        });
        generatedCu.addType(generatedClass);

        writeGeneratedClass(enclosingClass, outputClassName, generatedCu.toString());
    }

    // -------------------------------------------------------------------------
    // Validation helpers
    // -------------------------------------------------------------------------

    /**
     * Parses {@link Permute#strings()} into a {@code Map<String, String>} of
     * constant bindings, for use in pre-generation annotation string validation.
     * Entries that are malformed (no {@code =}) are silently skipped — the full
     * format check is done separately by {@link #validateStrings}.
     */
    private static Map<String, String> buildStringConstants(Permute permute) {
        Map<String, String> constants = new HashMap<>();
        for (String entry : permute.strings()) {
            int sep = entry.indexOf('=');
            if (sep > 0) {
                constants.put(entry.substring(0, sep).trim(), entry.substring(sep + 1));
            }
        }
        return constants;
    }

    /**
     * Validates that every entry in {@code @Permute strings} has the required
     * {@code "key=value"} format with a non-empty key that does not conflict with
     * {@code varName} or any {@code extraVars} variable name.
     */
    private boolean validateStrings(Permute permute, Element element, AnnotationMirror mirror) {
        for (String entry : permute.strings()) {
            int sep = entry.indexOf('=');
            if (sep < 0) {
                error(String.format(
                        "@Permute strings entry \"%s\" is malformed — each entry must be in \"key=value\" format",
                        entry),
                        element, mirror, findAnnotationValue(mirror, "strings"));
                return false;
            }
            String key = entry.substring(0, sep).trim();
            if (key.isEmpty()) {
                error(String.format(
                        "@Permute strings entry \"%s\" has an empty key — key must be non-empty",
                        entry),
                        element, mirror, findAnnotationValue(mirror, "strings"));
                return false;
            }
            if (key.equals(permute.varName())) {
                error(String.format(
                        "@Permute strings key \"%s\" conflicts with varName \"%s\" — use a different name",
                        key, permute.varName()),
                        element, mirror, findAnnotationValue(mirror, "strings"));
                return false;
            }
            for (PermuteVar extra : permute.extraVars()) {
                if (key.equals(extra.varName())) {
                    error(String.format(
                            "@Permute strings key \"%s\" conflicts with extraVars varName \"%s\" — use a different name",
                            key, extra.varName()),
                            element, mirror, findAnnotationValue(mirror, "strings"));
                    return false;
                }
            }
        }
        return true;
    }

    /**
     * Validates each {@link PermuteVar} in {@code extraVars}: range must be valid,
     * and variable names must not conflict with {@code varName}, each other, or any
     * {@code strings} key.
     */
    private boolean validateExtraVars(Permute permute, Element element, AnnotationMirror mirror) {
        Set<String> seen = new HashSet<>();
        seen.add(permute.varName());
        for (String entry : permute.strings()) {
            int sep = entry.indexOf('=');
            if (sep > 0)
                seen.add(entry.substring(0, sep).trim());
        }

        for (PermuteVar extra : permute.extraVars()) {
            // values XOR from/to validation for @PermuteVar
            boolean extraHasValues = extra.values() != null && extra.values().length > 0;
            boolean extraHasFrom = !extra.from().isEmpty();
            boolean extraHasTo = !extra.to().isEmpty();

            if (extraHasValues && (extraHasFrom || extraHasTo)) {
                error(String.format(
                        "@PermuteVar \"%s\" 'values' and 'from'/'to' are mutually exclusive — use one or the other",
                        extra.varName()),
                        element, mirror, findAnnotationValue(mirror, "extraVars"));
                return false;
            }
            if (!extraHasValues && (!extraHasFrom || !extraHasTo)) {
                error(String.format(
                        "@PermuteVar \"%s\" requires either 'values' (non-empty) or both 'from' and 'to'",
                        extra.varName()),
                        element, mirror, findAnnotationValue(mirror, "extraVars"));
                return false;
            }

            // Note: extra.from()/to() are now String — evaluate with baseCtx for validation
            // Use a simple parse attempt; full evaluation happens in buildAllCombinations
            if (!extraHasValues) {
                try {
                    int extraFrom = Integer.parseInt(extra.from().trim());
                    int extraTo = Integer.parseInt(extra.to().trim());
                    if (extraFrom > extraTo) {
                        error(String.format(
                                "@PermuteVar \"%s\" has invalid range: from=%d is greater than to=%d",
                                extra.varName(), extraFrom, extraTo),
                                element, mirror, findAnnotationValue(mirror, "extraVars"));
                        return false;
                    }
                } catch (NumberFormatException ignored) {
                    // Expression-based from/to — skip static validation, will fail at eval time
                }
            }
            if (seen.contains(extra.varName())) {
                error(String.format(
                        "@PermuteVar varName \"%s\" conflicts with an existing variable name" +
                                " — each variable name must be unique across varName, extraVars, and strings",
                        extra.varName()),
                        element, mirror, findAnnotationValue(mirror, "extraVars"));
                return false;
            }
            seen.add(extra.varName());
        }
        return true;
    }

    // -------------------------------------------------------------------------
    // Source parsing
    // -------------------------------------------------------------------------

    /**
     * Reads the source of the annotated element via the compiler Trees API.
     * Uses {@code getCharContent} so this works for both file-based and in-memory
     * sources (the latter is used by compile-testing in unit tests).
     */
    private CompilationUnit parseSource(TypeElement typeElement) {
        try {
            TreePath path = trees.getPath(typeElement);
            String source = path.getCompilationUnit().getSourceFile()
                    .getCharContent(true).toString();
            return StaticJavaParser.parse(source);
        } catch (IOException e) {
            processingEnv.getMessager().printMessage(
                    Diagnostic.Kind.ERROR,
                    "Failed to parse source for @Permute class: " + e.getMessage(),
                    typeElement);
            return null;
        }
    }

    // -------------------------------------------------------------------------
    // Error-reporting helpers
    // -------------------------------------------------------------------------

    private static AnnotationMirror findAnnotationMirror(Element element, String fqn) {
        for (AnnotationMirror mirror : element.getAnnotationMirrors()) {
            if (((TypeElement) mirror.getAnnotationType().asElement())
                    .getQualifiedName().contentEquals(fqn)) {
                return mirror;
            }
        }
        return null;
    }

    private static AnnotationValue findAnnotationValue(AnnotationMirror mirror, String attribute) {
        if (mirror == null)
            return null;
        for (Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry : mirror.getElementValues()
                .entrySet()) {
            if (entry.getKey().getSimpleName().contentEquals(attribute)) {
                return entry.getValue();
            }
        }
        return null;
    }

    private void error(String message, Element element, AnnotationMirror mirror, AnnotationValue value) {
        if (mirror != null && value != null) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, message, element, mirror, value);
        } else if (mirror != null) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, message, element, mirror);
        } else {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, message, element);
        }
    }

    /**
     * Processes {@code @PermuteMethod} annotations in APT mode.
     *
     * <p>
     * For each method annotated with {@code @PermuteMethod}, evaluates the inner
     * variable range using the outer permutation context, then for each {@code j}
     * value in that range clones the method, evaluates any {@code @PermuteReturn}
     * annotation (return type only — no boundary omission), strips {@code @PermuteMethod},
     * and adds the resulting overload to the class. The original sentinel method is removed.
     *
     * <p>
     * Boundary omission is driven by the {@code to} expression: when
     * {@code to < from} (e.g. {@code to = "${max - i}"} with {@code i = max}),
     * the inner loop produces zero iterations, so no overloads are emitted.
     */
    private void applyPermuteMethodApt(ClassOrInterfaceDeclaration classDecl,
            EvaluationContext ctx,
            Permute permute,
            TypeElement element) {

        List<MethodDeclaration> toRemove = new ArrayList<>();
        List<MethodDeclaration> toAdd = new ArrayList<>();

        classDecl.getMethods().forEach(method -> {
            // Find @PermuteMethod annotation
            Optional<NormalAnnotationExpr> pmAnnOpt = method.getAnnotations().stream()
                    .filter(a -> {
                        String n = a.getNameAsString();
                        return (n.equals("PermuteMethod") || n.equals("io.quarkiverse.permuplate.PermuteMethod"))
                                && a instanceof NormalAnnotationExpr;
                    })
                    .map(a -> (NormalAnnotationExpr) a)
                    .findFirst();
            if (pmAnnOpt.isEmpty())
                return;

            NormalAnnotationExpr pmAnn = pmAnnOpt.get();
            String varName = getAnnAttr(pmAnn, "varName");
            String fromStr = getAnnAttr(pmAnn, "from");
            String toStr = getAnnAttr(pmAnn, "to");
            String nameTempl = getAnnAttr(pmAnn, "name");

            if (varName == null || varName.isEmpty())
                return;

            // Evaluate from
            int fromVal;
            try {
                fromVal = ctx.evaluateInt(fromStr == null || fromStr.isEmpty() ? "1" : fromStr);
            } catch (Exception ignored) {
                fromVal = 1;
            }

            // Evaluate to: infer as @Permute.to - currentI when not explicit
            int toVal;
            if (toStr == null || toStr.isEmpty()) {
                // Infer: @Permute.to - current value of primary variable
                try {
                    int currentI = ctx.evaluateInt(permute.varName());
                    int outerTo = ctx.evaluateInt(permute.to());
                    toVal = outerTo - currentI;
                } catch (Exception ignored) {
                    toVal = fromVal - 1;
                }
            } else {
                try {
                    toVal = ctx.evaluateInt(toStr);
                } catch (Exception ignored) {
                    return;
                }
            }

            toRemove.add(method);

            // Track whether the original method has @PermuteReturn — used in j-loop below.
            // applyPermuteReturnSimple removes the annotation from clones that had it, so we
            // check the original method before cloning.
            boolean originalHasExplicitReturn = method.getAnnotations().stream().anyMatch(
                    a -> a.getNameAsString().equals("PermuteReturn")
                            || a.getNameAsString().equals("io.quarkiverse.permuplate.PermuteReturn"));

            // Collect class-level declared type params for j-based growing-tip detection.
            // These are the type params of the CURRENT generated class (after @PermuteTypeParam
            // expansion). Undeclared T+number vars in method return/param types are the growing tip.
            java.util.Set<String> declaredTypeParams = new java.util.LinkedHashSet<>();
            classDecl.getTypeParameters().forEach(tp -> declaredTypeParams.add(tp.getNameAsString()));

            for (int j = fromVal; j <= toVal; j++) {
                EvaluationContext innerCtx = ctx.withVariable(varName, j);
                MethodDeclaration clone = method.clone();

                // Strip @PermuteMethod from clone
                clone.getAnnotations().removeIf(a -> {
                    String n = a.getNameAsString();
                    return n.equals("PermuteMethod") || n.equals("io.quarkiverse.permuplate.PermuteMethod");
                });

                // Expand method-level @PermuteTypeParam with the (i,k) inner context
                io.quarkiverse.permuplate.core.PermuteTypeParamTransformer
                        .transformMethod(clone, innerCtx, processingEnv.getMessager(), element);

                // Apply @PermuteReturn: evaluate return type (no boundary omission)
                applyPermuteReturnSimple(clone, innerCtx, element);

                // J-based implicit type expansion: expand T+number growing tips by (j-1).
                // Fires only when the original method had no explicit @PermuteReturn
                // (explicit return types are already fully resolved by applyPermuteReturnSimple).
                // j=1 is always a no-op (offset=0).
                if (!originalHasExplicitReturn) {
                    expandMethodTypesForJ(clone, declaredTypeParams, j);
                }

                // Apply @PermuteDeclr on parameters with innerCtx
                io.quarkiverse.permuplate.core.PermuteDeclrTransformer
                        .processMethodParamDeclr(clone, innerCtx);

                // Apply @PermuteBody with innerCtx so body templates can reference
                // the @PermuteMethod inner variable.
                {
                    com.github.javaparser.ast.body.ClassOrInterfaceDeclaration tmpBody = new com.github.javaparser.ast.body.ClassOrInterfaceDeclaration();
                    tmpBody.addMember(clone);
                    io.quarkiverse.permuplate.core.PermuteBodyTransformer.transform(tmpBody, innerCtx);
                    if (!tmpBody.getMethods().isEmpty())
                        clone = tmpBody.getMethods().get(0);
                }

                // Apply name template if set
                if (nameTempl != null && !nameTempl.isEmpty()) {
                    try {
                        clone.setName(innerCtx.evaluate(nameTempl));
                    } catch (Exception ignored) {
                    }
                }

                toAdd.add(clone);
            }
        });

        toRemove.forEach(m -> classDecl.getMembers().removeIf(member -> member == m));
        toAdd.forEach(classDecl::addMember);
    }

    /**
     * Applies a single {@code @PermuteReturn} annotation on a method in APT mode,
     * evaluating the return type with the given context. No boundary omission is
     * performed — the caller controls whether to generate the method.
     */
    private void applyPermuteReturnSimple(MethodDeclaration method,
            EvaluationContext ctx,
            TypeElement element) {

        Optional<NormalAnnotationExpr> annOpt = method.getAnnotations().stream()
                .filter(a -> {
                    String n = a.getNameAsString();
                    return (n.equals("PermuteReturn") || n.equals("io.quarkiverse.permuplate.PermuteReturn"))
                            && a instanceof NormalAnnotationExpr;
                })
                .map(a -> (NormalAnnotationExpr) a)
                .findFirst();

        if (annOpt.isEmpty())
            return;

        NormalAnnotationExpr ann = annOpt.get();
        String classNameTemplate = getAnnAttr(ann, "className");
        String typeArgVarName = getAnnAttr(ann, "typeArgVarName");
        String typeArgFrom = getAnnAttr(ann, "typeArgFrom");
        String typeArgTo = getAnnAttr(ann, "typeArgTo");
        String typeArgName = getAnnAttr(ann, "typeArgName");
        String typeArgs = getAnnAttr(ann, "typeArgs");

        if (classNameTemplate == null || classNameTemplate.isEmpty())
            return;

        String evaluatedClassName;
        try {
            evaluatedClassName = ctx.evaluate(classNameTemplate);
        } catch (Exception e) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                    "@PermuteReturn: cannot evaluate className \"" + classNameTemplate
                            + "\": " + e.getMessage(),
                    element);
            return;
        }

        String returnTypeStr = buildReturnTypeStr(evaluatedClassName,
                typeArgVarName, typeArgFrom, typeArgTo, typeArgName, typeArgs, ctx);

        try {
            method.setType(StaticJavaParser.parseType(returnTypeStr));
        } catch (Exception e) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                    "@PermuteReturn: cannot parse computed return type \"" + returnTypeStr
                            + "\": " + e.getMessage(),
                    element);
            return;
        }

        // Remove @PermuteReturn annotation from the method
        method.getAnnotations().removeIf(a -> a == ann);
    }

    /**
     * Processes @PermuteReturn annotations on methods:
     * - Validates V2 (typeArgVarName requires typeArgTo+typeArgName) and V3 (from > to) and V6 (typeArgs+typeArgVarName)
     * - Evaluates className; applies boundary omission (omit method if class not in generated set, unless when="true")
     * - Replaces the method return type with the computed type
     * - Removes @PermuteReturn from the method
     */
    private void applyPermuteReturn(ClassOrInterfaceDeclaration classDecl,
            EvaluationContext ctx,
            Set<String> generatedSet,
            TypeElement element) {

        List<MethodDeclaration> toRemove = new ArrayList<>();

        classDecl.getMethods().forEach(method -> {
            // Find @PermuteReturn on this method
            Optional<NormalAnnotationExpr> annOpt = method.getAnnotations().stream()
                    .filter(a -> {
                        String n = a.getNameAsString();
                        return (n.equals("PermuteReturn") || n.equals("io.quarkiverse.permuplate.PermuteReturn"))
                                && a instanceof NormalAnnotationExpr;
                    })
                    .map(a -> (NormalAnnotationExpr) a)
                    .findFirst();

            if (annOpt.isEmpty())
                return;

            NormalAnnotationExpr ann = annOpt.get();

            // Read attributes
            String classNameTemplate = getAnnAttr(ann, "className");
            String typeArgVarName = getAnnAttr(ann, "typeArgVarName");
            String typeArgTo = getAnnAttr(ann, "typeArgTo");
            String typeArgName = getAnnAttr(ann, "typeArgName");
            String typeArgs = getAnnAttr(ann, "typeArgs");
            String whenExpr = getAnnAttr(ann, "when");
            String alwaysEmitAttr = getAnnAttr(ann, "alwaysEmit");
            String typeArgFrom = getAnnAttr(ann, "typeArgFrom");

            if (classNameTemplate == null || classNameTemplate.isEmpty())
                return;

            // V6: typeArgs and typeArgVarName both set
            if (typeArgVarName != null && !typeArgVarName.isEmpty()
                    && typeArgs != null && !typeArgs.isEmpty()) {
                processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                        "@PermuteReturn: typeArgs and typeArgVarName are mutually exclusive — use one or the other",
                        element);
                return;
            }

            // V2: typeArgVarName requires typeArgTo and typeArgName
            if (typeArgVarName != null && !typeArgVarName.isEmpty()) {
                if (typeArgTo == null || typeArgTo.isEmpty() || typeArgName == null || typeArgName.isEmpty()) {
                    processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                            "@PermuteReturn: typeArgVarName requires both typeArgTo and typeArgName to be specified.",
                            element);
                    return;
                }
            }

            // Evaluate className
            String evaluatedClassName;
            try {
                evaluatedClassName = ctx.evaluate(classNameTemplate);
            } catch (Exception e) {
                processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                        "@PermuteReturn: cannot evaluate className \"" + classNameTemplate + "\": " + e.getMessage(),
                        element);
                return;
            }

            // V3: typeArgFrom > typeArgTo
            if (typeArgVarName != null && !typeArgVarName.isEmpty()
                    && typeArgTo != null && !typeArgTo.isEmpty()) {
                try {
                    int fromVal = ctx.evaluateInt(typeArgFrom == null || typeArgFrom.isEmpty() ? "1" : typeArgFrom);
                    int toVal = ctx.evaluateInt(typeArgTo);
                    if (fromVal > toVal) {
                        processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                                "@PermuteReturn has invalid type argument range: from=" + fromVal
                                        + " is greater than to=" + toVal,
                                element);
                        return;
                    }
                } catch (Exception ignored) {
                }
            }

            // Boundary omission check
            boolean shouldGenerate;
            if ("true".equals(alwaysEmitAttr)) {
                shouldGenerate = true;
            } else if (whenExpr == null || whenExpr.isEmpty()) {
                shouldGenerate = generatedSet.contains(evaluatedClassName);
            } else {
                try {
                    // Wrap in ${...} for JEXL evaluation (same convention as EvaluationContext.evaluateInt).
                    // Boolean.parseBoolean handles both string "true"/"false" and boolean true/false from JEXL.
                    // Falls back to boundary-omission behaviour on exception (e.g. malformed expression).
                    String evaluated = ctx.evaluate("${" + whenExpr + "}");
                    shouldGenerate = Boolean.parseBoolean(evaluated);
                } catch (Exception ignored) {
                    shouldGenerate = generatedSet.contains(evaluatedClassName);
                }
            }

            if (!shouldGenerate) {
                toRemove.add(method);
                return;
            }

            // Build return type string
            String returnTypeStr = buildReturnTypeStr(evaluatedClassName,
                    typeArgVarName, typeArgFrom, typeArgTo, typeArgName, typeArgs, ctx);

            // Replace the method return type
            try {
                method.setType(StaticJavaParser.parseType(returnTypeStr));
            } catch (Exception e) {
                processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                        "@PermuteReturn: cannot parse computed return type \"" + returnTypeStr
                                + "\": " + e.getMessage(),
                        element);
                return;
            }

            // Remove @PermuteReturn annotation from the method
            method.getAnnotations().removeIf(a -> a == ann);
        });

        // Remove boundary-omitted methods
        toRemove.forEach(m -> classDecl.getMembers().removeIf(member -> member == m));
    }

    /** Builds the return type string from className + type argument configuration. */
    private String buildReturnTypeStr(String className,
            String typeArgVarName, String typeArgFrom, String typeArgTo,
            String typeArgName, String typeArgs, EvaluationContext ctx) {

        // typeArgs: full JEXL expression for the complete type arg list
        if (typeArgs != null && !typeArgs.isEmpty()) {
            try {
                String evaluated = ctx.evaluate("${" + typeArgs + "}");
                return evaluated.isEmpty() ? className : className + "<" + evaluated + ">";
            } catch (Exception ignored) {
                return className;
            }
        }

        // typeArgVarName loop
        if (typeArgVarName == null || typeArgVarName.isEmpty()) {
            return className; // raw return type (no type args)
        }

        String from = (typeArgFrom == null || typeArgFrom.isEmpty()) ? "1" : typeArgFrom;
        try {
            int fromVal = ctx.evaluateInt(from);
            int toVal = ctx.evaluateInt(typeArgTo);
            StringBuilder sb = new StringBuilder(className).append("<");
            for (int j = fromVal; j <= toVal; j++) {
                if (j > fromVal)
                    sb.append(", ");
                sb.append(ctx.withVariable(typeArgVarName, j).evaluate(typeArgName));
            }
            return sb.append(">").toString();
        } catch (Exception ignored) {
            return className;
        }
    }

    /** Extracts a named attribute value from a NormalAnnotationExpr, stripping quotes. Returns null if absent. */
    private static String getAnnAttr(NormalAnnotationExpr ann, String attrName) {
        for (MemberValuePair pair : ann.getPairs()) {
            if (pair.getNameAsString().equals(attrName)) {
                return io.quarkiverse.permuplate.core.PermuteDeclrTransformer
                        .stripQuotes(pair.getValue().toString());
            }
        }
        return null;
    }

    // =========================================================================
    // Extends expansion helpers
    // =========================================================================

    /** Returns the substring of name up to (but not including) its first digit. */
    private static String prefixBeforeFirstDigit(String name) {
        for (int i = 0; i < name.length(); i++) {
            if (Character.isDigit(name.charAt(i)))
                return name.substring(0, i);
        }
        return name;
    }

    /** Returns the first contiguous sequence of digits in name as an int, or -1 if none. */
    private static int firstEmbeddedNumber(String name) {
        int start = -1;
        for (int i = 0; i < name.length(); i++) {
            if (Character.isDigit(name.charAt(i))) {
                start = i;
                break;
            }
        }
        if (start < 0)
            return -1;
        int end = start;
        while (end < name.length() && Character.isDigit(name.charAt(end)))
            end++;
        try {
            return Integer.parseInt(name.substring(start, end));
        } catch (NumberFormatException e) {
            return -1;
        }
    }

    /** Replaces the first contiguous digit sequence in name with newNum. */
    private static String replaceFirstEmbeddedNumber(String name, int newNum) {
        int start = -1;
        for (int i = 0; i < name.length(); i++) {
            if (Character.isDigit(name.charAt(i))) {
                start = i;
                break;
            }
        }
        if (start < 0)
            return name;
        int end = start;
        while (end < name.length() && Character.isDigit(name.charAt(end)))
            end++;
        return name.substring(0, start) + newNum + name.substring(end);
    }

    /** Returns true if s matches the T+number pattern (e.g. "T1", "T23"). */
    private static boolean isTNumberVar(String s) {
        if (s == null || s.length() < 2 || s.charAt(0) != 'T')
            return false;
        for (int i = 1; i < s.length(); i++) {
            if (!Character.isDigit(s.charAt(i)))
                return false;
        }
        return true;
    }

    /** Record holding parsed return type info: base class name and type arguments. */
    private record ReturnTypeInfo(String baseClass, java.util.List<String> typeArgs) {
    }

    /**
     * Parses "Step2<T1, T2>" into ReturnTypeInfo("Step2", ["T1","T2"]).
     * Handles nested generics via depth-aware comma splitting.
     */
    private static ReturnTypeInfo parseReturnTypeInfo(String returnType) {
        int lt = returnType.indexOf('<');
        if (lt < 0)
            return new ReturnTypeInfo(returnType.trim(), java.util.List.of());
        String base = returnType.substring(0, lt).trim();
        String argsStr = returnType.substring(lt + 1, returnType.lastIndexOf('>')).trim();
        if (argsStr.isEmpty())
            return new ReturnTypeInfo(base, java.util.List.of());
        java.util.List<String> args = new java.util.ArrayList<>();
        int depth = 0, start = 0;
        for (int i = 0; i < argsStr.length(); i++) {
            char c = argsStr.charAt(i);
            if (c == '<')
                depth++;
            else if (c == '>')
                depth--;
            else if (c == ',' && depth == 0) {
                args.add(argsStr.substring(start, i).trim());
                start = i + 1;
            }
        }
        args.add(argsStr.substring(start).trim());
        return new ReturnTypeInfo(base, args);
    }

    /** Extracts numeric suffix from class name (e.g. "Chain3" → 3). Returns -1 if none. */
    private static int classNameSuffix(String name) {
        int i = name.length() - 1;
        if (i < 0 || !Character.isDigit(name.charAt(i)))
            return -1;
        while (i > 0 && Character.isDigit(name.charAt(i - 1)))
            i--;
        try {
            return Integer.parseInt(name.substring(i));
        } catch (Exception ignored) {
            return -1;
        }
    }

    /** Strips numeric suffix from class name (e.g. "Chain3" → "Chain"). */
    private static String stripNumericSuffix(String name) {
        int i = name.length() - 1;
        if (i < 0 || !Character.isDigit(name.charAt(i)))
            return name;
        while (i > 0 && Character.isDigit(name.charAt(i - 1)))
            i--;
        return name.substring(0, i);
    }

    /** Collects method keys that already have explicit @PermuteReturn (to exclude from inference). */
    private static java.util.Set<String> collectExplicitReturnMethods(
            com.github.javaparser.ast.body.TypeDeclaration<?> classDecl) {
        java.util.Set<String> keys = new java.util.HashSet<>();
        classDecl.getMethods().forEach(m -> m.getAnnotations().stream()
                .filter(a -> a.getNameAsString().equals("PermuteReturn")
                        || a.getNameAsString().equals("io.quarkiverse.permuplate.PermuteReturn"))
                .findFirst()
                .ifPresent(a -> keys.add(m.getNameAsString() + m.getParameters().toString())));
        return keys;
    }

    /**
     * Applies implicit return type inference to methods without @PermuteReturn.
     *
     * <p>
     * Designed for APT mode where {@code @PermuteTypeParam} has already expanded the class type
     * parameters. After expansion, the generated class (e.g. {@code Chain3<T1,T2,T3>}) has more type
     * params than the template ({@code Chain2<T1,T2>}), but the method return type still reflects
     * the template's arity (e.g. {@code Chain2<T1,T2>}).
     *
     * <p>
     * Fires when BOTH conditions hold:
     * <ol>
     * <li>The return type base class belongs to the same family as the generated classes
     * (same name prefix before the trailing digits, e.g. "Chain" for "Chain2"/"Chain3").</li>
     * <li>The return type has fewer type args than the current class has type parameters —
     * indicating the return type still reflects the pre-expansion arity.</li>
     * </ol>
     *
     * <p>
     * When inference fires, the return type is updated to the CURRENT class (self-referential)
     * with all current type params as arguments. Boundary omission: if the NEXT class in the
     * family (currentSuffix + 1) is not in allGeneratedNames, the method is removed — this is
     * the leaf-node pattern (last class in the range has the self-returning method omitted).
     */
    private static void applyImplicitInference(
            com.github.javaparser.ast.body.ClassOrInterfaceDeclaration classDecl,
            java.util.Set<String> allGeneratedNames,
            java.util.Set<String> explicitReturnMethods) {

        // All declared type parameter names for the generated class (after @PermuteTypeParam expansion)
        java.util.List<String> currentTypeParams = new java.util.ArrayList<>();
        classDecl.getTypeParameters().forEach(tp -> currentTypeParams.add(tp.getNameAsString()));

        int currentSuffix = classNameSuffix(classDecl.getNameAsString());
        if (currentSuffix < 0)
            return; // Generated class has no numeric suffix — inference does not apply

        String currentClassName = classDecl.getNameAsString();
        String currentFamilyPrefix = stripNumericSuffix(currentClassName);

        java.util.List<com.github.javaparser.ast.body.MethodDeclaration> toRemove = new java.util.ArrayList<>();

        classDecl.getMethods().forEach(method -> {
            String methodKey = method.getNameAsString() + method.getParameters().toString();
            if (explicitReturnMethods.contains(methodKey))
                return;

            String returnTypeStr = method.getTypeAsString();
            if (returnTypeStr.equals("void") || returnTypeStr.equals("Object"))
                return;

            ReturnTypeInfo info = parseReturnTypeInfo(returnTypeStr);
            if (info == null)
                return;

            // Condition 1: return type base class must be in the same family as the generated
            // classes (same name prefix before trailing digits).
            // E.g. "Chain2" has prefix "Chain"; matches generated "Chain3", "Chain4".
            String returnBasePrefix = stripNumericSuffix(info.baseClass());
            if (returnBasePrefix.isEmpty() || returnBasePrefix.equals(info.baseClass()))
                return; // base class has no numeric suffix — not a numbered family
            if (!returnBasePrefix.equals(currentFamilyPrefix))
                return; // different family

            // Condition 2: the return type has fewer type args than the current class has type
            // params. This indicates the return type still reflects the pre-expansion arity and
            // should be updated to the expanded form.
            if (info.typeArgs().size() >= currentTypeParams.size())
                return;

            // Boundary omission: the NEXT class in the family must exist in the generated set.
            // The current class is the "self" return. If there is no next class, this class
            // is the leaf node and the method is omitted (same leaf-node pattern as @PermuteReturn).
            String nextClassName = currentFamilyPrefix + (currentSuffix + 1);
            if (!allGeneratedNames.contains(nextClassName)) {
                toRemove.add(method);
                return;
            }

            // Update return type to the CURRENT class with all current type params (self-referential)
            String newReturnType = currentClassName + "<" + String.join(", ", currentTypeParams) + ">";
            try {
                method.setType(com.github.javaparser.StaticJavaParser.parseType(newReturnType));
            } catch (Exception ignored) {
                return;
            }
        });

        toRemove.forEach(m -> classDecl.getMembers().removeIf(member -> member == m));
    }

    /**
     * Expands the extends clause of a generated class to match its current arity.
     *
     * Fires only when the extends base class shares the same name prefix and embedded
     * number as the template class. Replaces the embedded number with currentEmbeddedNum
     * (same-N formula: Join3First extends Join3Second, not Join4Second).
     *
     * Branch 1 — all T+number type args: builds T1..T(currentEmbeddedNum).
     * Branch 2 — alpha/mixed: extends type args must be a prefix of postG1TypeParams;
     * uses the full postG1TypeParams list.
     *
     * Third-party base classes (different name prefix) are skipped.
     */
    private static void applyExtendsExpansion(
            com.github.javaparser.ast.body.ClassOrInterfaceDeclaration classDecl,
            String templateName,
            int templateEmbeddedNum,
            int currentEmbeddedNum,
            java.util.List<String> postG1TypeParams) {

        if (templateEmbeddedNum < 0 || currentEmbeddedNum < 0)
            return;
        String templatePrefix = prefixBeforeFirstDigit(templateName);
        int newNum = currentEmbeddedNum;

        com.github.javaparser.ast.NodeList<com.github.javaparser.ast.type.ClassOrInterfaceType> extended = classDecl
                .getExtendedTypes();

        for (int idx = 0; idx < extended.size(); idx++) {
            com.github.javaparser.ast.type.ClassOrInterfaceType ext = extended.get(idx);
            String baseName = ext.getNameAsString();

            // Only expand siblings: same prefix-before-digit as template
            if (!prefixBeforeFirstDigit(baseName).equals(templatePrefix))
                continue;

            // Only expand when base class has the same embedded number as template
            int extNum = firstEmbeddedNumber(baseName);
            if (extNum < 0 || extNum != templateEmbeddedNum)
                continue;

            java.util.Optional<com.github.javaparser.ast.NodeList<com.github.javaparser.ast.type.Type>> typeArgsOpt = ext
                    .getTypeArguments();
            if (typeArgsOpt.isEmpty() || typeArgsOpt.get().isEmpty())
                continue;

            java.util.List<String> extArgNames = typeArgsOpt.get().stream()
                    .map(com.github.javaparser.ast.type.Type::asString)
                    .collect(java.util.stream.Collectors.toList());

            // Determine new type args
            java.util.List<String> newTypeArgNames;
            boolean allTNumber = extArgNames.stream().allMatch(PermuteProcessor::isTNumberVar);
            if (allTNumber) {
                newTypeArgNames = new java.util.ArrayList<>();
                for (int t = 1; t <= newNum; t++)
                    newTypeArgNames.add("T" + t);
            } else {
                // Alpha/mixed: extends args must be a prefix of postG1TypeParams
                boolean isPrefix = extArgNames.size() <= postG1TypeParams.size()
                        && java.util.stream.IntStream.range(0, extArgNames.size())
                                .allMatch(k -> extArgNames.get(k).equals(postG1TypeParams.get(k)));
                if (!isPrefix)
                    continue;
                newTypeArgNames = postG1TypeParams;
            }

            String newBaseName = replaceFirstEmbeddedNumber(baseName, newNum);
            String newExtStr = newBaseName + "<" + String.join(", ", newTypeArgNames) + ">";
            try {
                extended.set(idx, com.github.javaparser.StaticJavaParser.parseClassOrInterfaceType(newExtStr));
            } catch (Exception ignored) {
            }
        }
    }

    // =========================================================================
    // J-based @PermuteMethod type expansion helpers
    // =========================================================================

    /**
     * Increments the first contiguous digit sequence in name by offset.
     * E.g. incrementFirstEmbeddedNumber("JExpand2", 1) → "JExpand3".
     */
    private static String incrementFirstEmbeddedNumber(String name, int offset) {
        int start = -1;
        for (int i = 0; i < name.length(); i++) {
            if (Character.isDigit(name.charAt(i))) {
                start = i;
                break;
            }
        }
        if (start < 0)
            return name;
        int end = start;
        while (end < name.length() && Character.isDigit(name.charAt(end)))
            end++;
        int num = Integer.parseInt(name.substring(start, end));
        return name.substring(0, start) + (num + offset) + name.substring(end);
    }

    /**
     * Rebuilds the type argument list, expanding the growing tip from T(firstTipNum)
     * to T(newLastTipNum) while preserving fixed args in their original relative positions.
     *
     * <p>
     * Example: args=[T1, T2], declaredTypeParams={T1}, firstTipNum=2, newLastTipNum=3
     * → [T1, T2, T3]
     */
    private static java.util.List<String> buildExpandedTypeArgs(java.util.List<String> originalArgs,
            java.util.Set<String> declaredTypeParams,
            int firstTipNum, int newLastTipNum) {
        java.util.List<String> result = new java.util.ArrayList<>();
        boolean tipInserted = false;

        for (String arg : originalArgs) {
            boolean isTip = !declaredTypeParams.contains(arg) && isTNumberVar(arg);
            if (isTip && !tipInserted) {
                // Insert expanded tip: T(firstTipNum)..T(newLastTipNum)
                for (int t = firstTipNum; t <= newLastTipNum; t++) {
                    result.add("T" + t);
                }
                tipInserted = true;
            } else if (isTip) {
                // Additional tip vars from original — skip (already expanded above)
            } else {
                // Fixed arg — pass through
                result.add(arg);
            }
        }
        return result;
    }

    /**
     * Expands a single type string for the j-based inner loop (offset = j-1).
     * Finds undeclared T+number vars (growing tip), expands them, and increments
     * the first embedded integer in the base class name by offset.
     * Returns typeStr unchanged if no growing tip found.
     */
    private static String expandTypeStringForJ(String typeStr,
            java.util.Set<String> declaredTypeParams, int offset) {
        ReturnTypeInfo info = parseReturnTypeInfo(typeStr);
        if (info == null)
            return typeStr;

        java.util.List<String> growingTip = new java.util.ArrayList<>();
        for (String arg : info.typeArgs()) {
            if (!declaredTypeParams.contains(arg) && isTNumberVar(arg))
                growingTip.add(arg);
        }
        if (growingTip.isEmpty())
            return typeStr;

        int firstTipNum = Integer.parseInt(growingTip.get(0).substring(1));
        int newLastTipNum = firstTipNum + offset;

        java.util.List<String> newTypeArgs = buildExpandedTypeArgs(
                info.typeArgs(), declaredTypeParams, firstTipNum, newLastTipNum);
        String newBase = incrementFirstEmbeddedNumber(info.baseClass(), offset);
        return newTypeArgs.isEmpty() ? newBase : newBase + "<" + String.join(", ", newTypeArgs) + ">";
    }

    /**
     * Applies j-based implicit type expansion to a method's return type, parameter types,
     * and method-level type parameters.
     *
     * <p>
     * j=1 is always a no-op (offset=0). For j&gt;1, T+number vars that are NOT declared
     * at CLASS level (growing tip — including method-level type params that serve as sentinels)
     * are expanded by (j-1), the first embedded class-name number is incremented by (j-1),
     * and any new T+number vars introduced by the expansion are added to the method's type
     * parameter list.
     *
     * <p>
     * Only called for clones that did NOT have explicit @PermuteReturn.
     */
    private static void expandMethodTypesForJ(
            MethodDeclaration method,
            java.util.Set<String> classDeclaredTypeParams, int j) {
        if (j <= 1)
            return;
        int offset = j - 1;

        // Use ONLY class-level declared type params for tip detection.
        // Method-level type params (e.g. <T2>) are the sentinels / growing tip — they must NOT
        // be treated as declared, so that T2 in JConn2<T1, T2> is recognized as the growing tip.
        String rt = method.getTypeAsString();
        String newRt = expandTypeStringForJ(rt, classDeclaredTypeParams, offset);
        if (!newRt.equals(rt)) {
            try {
                method.setType(StaticJavaParser.parseType(newRt));
            } catch (Exception ignored) {
            }
        }

        method.getParameters().forEach(param -> {
            String pt = param.getTypeAsString();
            String newPt = expandTypeStringForJ(pt, classDeclaredTypeParams, offset);
            if (!newPt.equals(pt)) {
                try {
                    param.setType(StaticJavaParser.parseType(newPt));
                } catch (Exception ignored) {
                }
            }
        });

        // Add new T+number type params introduced by the expansion to the method's type param list.
        // Collect existing method-level type params (before we start adding) to prevent duplicates.
        java.util.Set<String> existingMethodTypeParams = new java.util.LinkedHashSet<>();
        method.getTypeParameters().forEach(tp -> existingMethodTypeParams.add(tp.getNameAsString()));

        ReturnTypeInfo expandedInfo = parseReturnTypeInfo(method.getTypeAsString());
        if (expandedInfo != null) {
            for (String arg : expandedInfo.typeArgs()) {
                if (isTNumberVar(arg)
                        && !classDeclaredTypeParams.contains(arg)
                        && !existingMethodTypeParams.contains(arg)) {
                    try {
                        method.addTypeParameter(com.github.javaparser.StaticJavaParser
                                .parseTypeParameter(arg));
                        existingMethodTypeParams.add(arg); // prevent duplicates
                    } catch (Exception ignored) {
                    }
                }
            }
        }
    }

    /**
     * Extracts all {@code @PermuteImport} value strings from the class declaration,
     * handling both single {@code @PermuteImport} and the {@code @PermuteImports}
     * repeatable container form.
     */
    private static java.util.List<String> collectPermuteImports(
            com.github.javaparser.ast.body.TypeDeclaration<?> classDecl) {
        java.util.List<String> imports = new java.util.ArrayList<>();
        classDecl.getAnnotations().forEach(ann -> {
            String name = ann.getNameAsString();
            if (name.equals("PermuteImport") || name.equals("io.quarkiverse.permuplate.PermuteImport")) {
                extractImportValue(ann).ifPresent(imports::add);
            } else if (name.equals("PermuteImports") || name.equals("io.quarkiverse.permuplate.PermuteImports")) {
                if (ann instanceof com.github.javaparser.ast.expr.NormalAnnotationExpr normal) {
                    normal.getPairs().stream()
                            .filter(p -> p.getNameAsString().equals("value"))
                            .findFirst()
                            .ifPresent(p -> {
                                com.github.javaparser.ast.expr.Expression val = p.getValue();
                                java.util.List<com.github.javaparser.ast.expr.Expression> elems = val instanceof com.github.javaparser.ast.expr.ArrayInitializerExpr arr
                                        ? arr.getValues()
                                        : java.util.List.of(val);
                                elems.forEach(e -> {
                                    if (e instanceof com.github.javaparser.ast.expr.AnnotationExpr ae) {
                                        extractImportValue(ae).ifPresent(imports::add);
                                    }
                                });
                            });
                }
            }
        });
        return imports;
    }

    private static java.util.Optional<String> extractImportValue(
            com.github.javaparser.ast.expr.AnnotationExpr ann) {
        if (ann instanceof com.github.javaparser.ast.expr.SingleMemberAnnotationExpr s) {
            return java.util.Optional.of(
                    io.quarkiverse.permuplate.core.PermuteDeclrTransformer
                            .stripQuotes(s.getMemberValue().toString()));
        }
        if (ann instanceof com.github.javaparser.ast.expr.NormalAnnotationExpr n) {
            return n.getPairs().stream()
                    .filter(p -> p.getNameAsString().equals("value"))
                    .findFirst()
                    .map(p -> io.quarkiverse.permuplate.core.PermuteDeclrTransformer
                            .stripQuotes(p.getValue().toString()));
        }
        return java.util.Optional.empty();
    }

    /**
     * Reads all @PermuteFilter expression strings from the given element via annotation mirrors.
     * Handles both the single-annotation case and the @PermuteFilters container.
     * Returns an empty list when no filters are present.
     */
    private List<String> readFilterExpressions(Element element) {
        List<String> result = new java.util.ArrayList<>();
        for (AnnotationMirror mirror : processingEnv.getElementUtils()
                .getAllAnnotationMirrors(element)) {
            TypeElement annType = (TypeElement) mirror.getAnnotationType().asElement();
            String fqn = annType.getQualifiedName().toString();
            if ("io.quarkiverse.permuplate.PermuteFilter".equals(fqn)) {
                mirror.getElementValues().forEach((k, v) -> {
                    if ("value".equals(k.getSimpleName().toString())) {
                        result.add(v.getValue().toString());
                    }
                });
            } else if ("io.quarkiverse.permuplate.PermuteFilters".equals(fqn)) {
                mirror.getElementValues().forEach((k, v) -> {
                    if ("value".equals(k.getSimpleName().toString())
                            && v.getValue() instanceof java.util.List<?> list) {
                        for (Object item : list) {
                            if (item instanceof AnnotationValue av
                                    && av.getValue() instanceof AnnotationMirror inner) {
                                inner.getElementValues().forEach((ik, iv) -> {
                                    if ("value".equals(ik.getSimpleName().toString())) {
                                        result.add(iv.getValue().toString());
                                    }
                                });
                            }
                        }
                    }
                });
            }
        }
        return result;
    }

    /**
     * Applies @PermuteFilter expressions to a list of combinations.
     * Returns the subset where ALL filter expressions evaluate to true.
     * On evaluation error, logs a warning and keeps the combination.
     */
    private List<Map<String, Object>> applyFilters(
            List<Map<String, Object>> combinations,
            List<String> filterExprs,
            Element element) {
        if (filterExprs.isEmpty())
            return combinations;
        return combinations.stream().filter(vars -> {
            EvaluationContext ctx = new EvaluationContext(vars);
            for (String expr : filterExprs) {
                try {
                    if (!ctx.evaluateBoolean(expr))
                        return false;
                } catch (Exception e) {
                    processingEnv.getMessager().printMessage(
                            javax.tools.Diagnostic.Kind.WARNING,
                            "@PermuteFilter expression error (combination kept): "
                                    + expr + " — " + e.getMessage(),
                            element);
                }
            }
            return true;
        }).collect(java.util.stream.Collectors.toList());
    }

    // =========================================================================
    // Template type lookup — handles class, interface, and record declarations
    // =========================================================================

    /**
     * Finds a class, interface, record, or enum by simple name in the given compilation unit.
     * Tries ClassOrInterfaceDeclaration first, then RecordDeclaration, then EnumDeclaration.
     */
    private static Optional<TypeDeclaration<?>> findTemplateType(
            CompilationUnit cu, String simpleName) {
        return cu.findFirst(ClassOrInterfaceDeclaration.class,
                c -> c.getNameAsString().equals(simpleName))
                .<TypeDeclaration<?>> map(c -> c)
                .or(() -> cu.findFirst(RecordDeclaration.class,
                        r -> r.getNameAsString().equals(simpleName)))
                .or(() -> cu.findFirst(EnumDeclaration.class,
                        e -> e.getNameAsString().equals(simpleName)));
    }

    private void writeGeneratedClass(TypeElement typeElement, String newClassName, String source) {
        // Determine package from the enclosing element.
        // For nested classes, getEnclosingElement() is the outer class, not a package —
        // walk up until we reach the package.
        Element enclosing = typeElement.getEnclosingElement();
        while (!(enclosing instanceof PackageElement)) {
            enclosing = enclosing.getEnclosingElement();
        }
        String packageName = ((PackageElement) enclosing).getQualifiedName().toString();
        String qualifiedName = packageName.isEmpty() ? newClassName : packageName + "." + newClassName;

        try {
            JavaFileObject file = processingEnv.getFiler().createSourceFile(qualifiedName, typeElement);
            try (Writer w = file.openWriter()) {
                w.write(source);
            }
            processingEnv.getMessager().printMessage(
                    Diagnostic.Kind.NOTE, "Generated " + qualifiedName, typeElement);
        } catch (IOException e) {
            String raw = e.getMessage() != null ? e.getMessage() : "";
            boolean isDuplicate = raw.contains("recreate") || raw.contains("already");
            String msg = isDuplicate
                    ? "Duplicate generated class " + qualifiedName
                            + " — @Permute className must include the permutation variable (e.g. \"Foo${i}\")"
                    : "Failed to write " + qualifiedName + ": " + raw;
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, msg, typeElement);
        }
    }
}
