package io.quarkiverse.permuplate.example.drools;

import io.quarkiverse.permuplate.Permute;
import io.quarkiverse.permuplate.PermuteConst;
import io.quarkiverse.permuplate.PermuteDeclr;
import io.quarkiverse.permuplate.PermuteExtends;
import io.quarkiverse.permuplate.PermuteParam;
import io.quarkiverse.permuplate.PermuteStatements;
import io.quarkiverse.permuplate.PermuteTypeParam;
import io.quarkiverse.permuplate.PermuteValue;

/**
 * Abstract base for the typed tuple hierarchy used by OOPath traversal.
 * Tuple0 is hand-written. Tuple1 is the template (kept via keepTemplate=true).
 * Tuple2..Tuple6 are generated by Permuplate from the Tuple1 template.
 *
 * <p>
 * Each TupleN adds one field ({@code a}, {@code b}, …) with a typed
 * getter/setter, and delegates out-of-range index access to its parent.
 */
public abstract class BaseTuple {
    protected int size;

    @SuppressWarnings("unchecked")
    public <T> T get(int index) {
        throw new IndexOutOfBoundsException(index);
    }

    @SuppressWarnings("unchecked")
    public <T> void set(int index, T t) {
        throw new IndexOutOfBoundsException(index);
    }

    public int size() {
        return size;
    }

    @SuppressWarnings({ "unchecked", "varargs" })
    public <T> T as(T... v) {
        Class<T> clazz = (Class<T>) v.getClass().getComponentType();
        try {
            Object[] args = new Object[size()];
            for (int i = 0; i < size(); i++) {
                args[i] = get(i);
            }
            for (java.lang.reflect.Constructor<?> ctor : clazz.getDeclaredConstructors()) {
                if (ctor.getParameterCount() == size()) {
                    ctor.setAccessible(true);
                    return (T) ctor.newInstance(args);
                }
            }
            throw new IllegalArgumentException(
                    "No constructor with " + size() + " parameters found on " + clazz.getName());
        } catch (IllegalArgumentException e) {
            throw e;
        } catch (Exception e) {
            throw new RuntimeException("as() projection failed for " + clazz.getName(), e);
        }
    }

    @SuppressWarnings("unchecked")
    static <F> F unchecked(Object o) {
        return (F) o;
    }

    public static class Tuple0 extends BaseTuple {
        public Tuple0() {
            this.size = 0;
        }

        @Override
        public <T> T get(int index) {
            throw new IndexOutOfBoundsException(index);
        }

        @Override
        public <T> void set(int index, T t) {
            throw new IndexOutOfBoundsException(index);
        }
    }

    @Permute(varName = "i", from = "2", to = "6", className = "Tuple${i}",
             inline = true, keepTemplate = true)
    @PermuteExtends(className = "Tuple${i-1}", typeArgs = "typeArgList(1, i-1, 'alpha')")
    public static class Tuple1<
            @PermuteTypeParam(varName = "k", from = "1", to = "${i}", name = "${alpha(k)}") A>
            extends BaseTuple {

        @PermuteDeclr(type = "${alpha(i)}", name = "${lower(i)}")
        protected A a;

        @PermuteValue(index = 0, value = "${i}")
        public Tuple1() {
            this.size = 1;
        }

        @PermuteStatements(position = "first", body = "super(${typeArgList(1, i-1, 'lower')});")
        @PermuteValue(index = 1, value = "${i}")
        public Tuple1(
                @PermuteParam(varName = "k", from = "1", to = "${i}", type = "${alpha(k)}", name = "${lower(k)}") A a) {
            this.a = a;
            this.size = 1;
        }

        @PermuteDeclr(type = "${alpha(i)}", name = "get${alpha(i)}")
        public A getA() {
            return a;
        }

        @PermuteDeclr(type = "", name = "set${alpha(i)}")
        public void setA(@PermuteDeclr(type = "${alpha(i)}", name = "${lower(i)}") A a) {
            this.a = a;
        }

        @Override
        public <T> T get(int index) {
            @PermuteConst("${i-1}") int idx = 0;
            if (index == idx)
                return unchecked(a);
            return super.get(index);
        }

        @Override
        public <T> void set(int index, T t) {
            @PermuteConst("${i-1}") int idx = 0;
            if (index == idx) {
                a = unchecked(t);
                return;
            }
            super.set(index, t);
        }
    }
}
