package io.quarkiverse.permuplate.example.drools;

import io.quarkiverse.permuplate.Permute;
import io.quarkiverse.permuplate.PermuteBody;
import io.quarkiverse.permuplate.PermuteDeclr;
import io.quarkiverse.permuplate.PermuteMethod;
import io.quarkiverse.permuplate.PermuteReturn;
import io.quarkiverse.permuplate.PermuteSelf;
import io.quarkiverse.permuplate.PermuteTypeParam;

/**
 * Container for the JoinFirst and JoinSecond class families generated by Permuplate.
 *
 * <p>Two template classes are declared here:
 * <ol>
 *   <li>{@code Join0Second} — generates {@code Join1Second..Join6Second}: the "gateway"
 *       class family with {@code join()} methods (both single-source and bi-linear).</li>
 *   <li>{@code Join0First} — generates {@code Join1First..Join6First}: the "full" class
 *       family with {@code filter()} and {@code fn()}, extending the corresponding Second.</li>
 * </ol>
 *
 * <p><b>Declaration order matters:</b> {@code Join0Second} is declared before {@code Join0First}
 * so that PermuteMojo processes it first. This ensures boundary omission on
 * {@code join()} (which references {@code Join${i+1}First}) sees the JoinFirst generated
 * names in {@code scanAllGeneratedClassNames()}.
 *
 * <p><b>END phantom type:</b> All generated classes carry an {@code END} type parameter
 * inherited from {@link BaseRuleBuilder}. For top-level rules END={@code Void}; for future
 * nested scopes ({@code not()}, {@code exists()}) END is the outer builder type, enabling
 * typed return via {@code end()}. See {@link BaseRuleBuilder} for the full semantics.
 *
 * <p><b>Bi-linear joins:</b> {@code join(JoinNSecond)} overloads on {@code Join0Second}
 * enable joining with a pre-built fact sub-network. The right chain executes independently
 * and its matched tuples are cross-producted with the current chain's tuples. This models
 * the Rete bi-linear beta node for node-sharing between rules that share a common sub-network.
 */
public class JoinBuilder {

    /**
     * Sealed marker interface for the {@code JoinNSecond} generated family.
     * Permits clause expanded by Permuplate's {@code expandSealedPermits} to list
     * all generated {@code Join1Second..Join6Second} classes.
     *
     * <p>Enables Java 21+ pattern dispatch:
     * <pre>{@code
     * JoinBuilderSecond<?, Ctx> builder = getBuilder();
     * switch (builder) {
     *     case Join1Second<?, Ctx> j -> handle1(j);
     *     case Join2Second<?, Ctx, ?> j -> handle2(j);
     *     // ...
     * }
     * }</pre>
     */
    public sealed interface JoinBuilderSecond<END, DS> permits Join0Second {}

    /**
     * Sealed marker interface for the {@code JoinNFirst} generated family.
     * Permits clause expanded by Permuplate's {@code expandSealedPermits} to list
     * all generated {@code Join1First..Join6First} classes.
     */
    public sealed interface JoinBuilderFirst<END, DS> permits Join0First {}

    /**
     * Template generating Join1Second through Join6Second.
     *
     * <p>Declared FIRST so PermuteMojo processes it before Join0First, ensuring
     * boundary omission on join() sees the complete generated-class set.
     *
     * <p>Contains two join() overloads:
     * <ul>
     *   <li>Single-source: {@code join(Function<DS, DataSource<B>>)} — typed via
     *       method-level {@code @PermuteTypeParam}; propagation renames B automatically.</li>
     *   <li>Bi-linear: {@code join(JoinNSecond<Void,DS,...>)} — generated by
     *       {@code @PermuteMethod(j)} for all valid right-chain arities. The pre-built
     *       chain always uses {@code Void} as END (no outer scope).</li>
     * </ul>
     */
    @Permute(varName = "i", from = "1", to = "6", className = "Join${i}Second",
             inline = true, keepTemplate = false)
    public static non-sealed class Join0Second<END, DS,
            @PermuteTypeParam(varName = "k", from = "1", to = "${i}", name = "${alpha(k)}") A>
            extends BaseRuleBuilder<END>
            implements JoinSecond<DS>, JoinBuilderSecond<END, DS> {

        protected final RuleDefinition<DS> rd;

        public Join0Second(END end, RuleDefinition<DS> rd) {
            super(end);
            this.rd = rd;
        }

        @Override
        public RuleDefinition<DS> getRuleDefinition() {
            return rd;
        }

        @SuppressWarnings("unchecked")
        private static <T> T cast(Object o) {
            return (T) o;
        }

        /**
         * Advances the arity by one fact type from a fresh data source.
         *
         * <p>{@code @PermuteTypeParam} renames {@code <B>} to the next alpha letter per arity
         * (B at i=1, C at i=2, …). Propagation automatically renames B in
         * {@code DataSource<B>} alongside the declaration — no {@code @PermuteDeclr} needed.
         *
         * <p>Boundary omission removes this from Join6Second — Join7First is not in the
         * generated set, so {@code @PermuteReturn} silently omits it at i=6.
         *
         * <p>Uses {@code @PermuteDeclr TYPE_USE} on the constructor to rename
         * {@code Join1First} to {@code Join${i+1}First} per permutation — no reflection needed.
         */
        @PermuteTypeParam(varName = "m", from = "${i+1}", to = "${i+1}", name = "${alpha(m)}")
        @PermuteReturn(className = "Join${i+1}First",
                       typeArgs = "'END, DS, ' + typeArgList(1, i+1, 'alpha')")
        public <B> Object join(java.util.function.Function<DS, DataSource<B>> source) {
            rd.addSource(source);
            return cast(new @PermuteDeclr(type = "Join${i+1}First") Join1First<>(end(), rd));
        }

        /**
         * Bi-linear join: joins with a pre-built fact sub-network.
         *
         * <p>The right chain (a pre-built {@code JoinNSecond} or {@code JoinNFirst} since
         * First extends Second) executes independently against the same ctx. Its matched
         * tuples are cross-producted with the current chain's tuples. The right chain's
         * internal filters apply only within the sub-network — they gate which of its
         * tuples enter the cross-product, not which combined tuples pass overall.
         *
         * <p>The pre-built chain always uses {@code Void} as END (no outer scope). This
         * is why the parameter type is {@code JoinNSecond<Void, DS, ...>} — the chain was
         * built at the top level and has no nested context to return to.
         *
         * <p>{@code to} is omitted: inferred as {@code @Permute.to - i = 6 - i}.
         * For i=1: j=1..5. For i=5: j=1. For i=6: empty range, no overloads generated.
         * Total bi-linear overloads across all arities: 15 (complete matrix).
         *
         * <p>{@code @PermuteTypeParam} inside {@code @PermuteMethod} (G4): expands the
         * sentinel {@code <C>} into j new alpha-named method type params (alpha(i+1)..alpha(i+j)).
         * {@code @PermuteDeclr} sets the parameter type to the correct {@code JoinNSecond} type.
         */
        @PermuteMethod(varName = "j", from = "1", name = "join")
        @PermuteReturn(className = "Join${i+j}First",
                       typeArgs = "'END, DS, ' + typeArgList(1, i+j, 'alpha')")
        public <@PermuteTypeParam(varName = "k", from = "${i+1}", to = "${i+j}",
                                   name = "${alpha(k)}") C> Object joinBilinear(
                @PermuteDeclr(type = "Join${j}Second<Void, DS, ${typeArgList(i+1, i+j, 'alpha')}>")
                Object secondChain) {
            @SuppressWarnings("unchecked")
            JoinSecond<DS> second = (JoinSecond<DS>) secondChain;
            rd.addBilinearSource(second.getRuleDefinition());
            return cast(new JoinBuilder.@PermuteDeclr(type = "Join${i+j}First") Join1First<>(end(), rd));
        }

        /**
         * Starts a negation scope (k=1) or existence scope (k=2).
         *
         * <p>Negation: the outer fact combination is valid ONLY IF this scope produces
         * zero matching tuples. Models "there is no X satisfying Y." Corresponds to
         * the Rete NegativeExistsNode pattern.
         *
         * <p>Existence: the outer fact combination is valid ONLY IF this scope produces
         * at least one matching tuple. Models "there exists an X satisfying Y."
         * Corresponds to the Rete PositiveExistsNode pattern.
         *
         * <p>Inside either scope: call {@code join()} to add sources, {@code filter()} to
         * add constraints, then {@code end()} to close the scope and return to the outer
         * builder at its original arity. The scope facts do NOT add to the outer chain.
         *
         * <p>Sandbox simplification: the scope evaluates independently of the specific
         * outer fact combination (runs against ctx globally). Full Drools tracks the
         * per-tuple connection via beta memory.
         */
        @PermuteMethod(varName = "k", from = "1", to = "2",
                       name = "${k == 1 ? 'not' : 'exists'}")
        @PermuteReturn(className = "${k == 1 ? 'NegationScope' : 'ExistenceScope'}",
                       typeArgs = "'Join' + i + 'Second<END, DS, ' + typeArgList(1, i, 'alpha') + '>, DS'",
                       alwaysEmit = true)
        @PermuteBody(body = "{ RuleDefinition<DS> scopeRd = new RuleDefinition<>(\"${k == 1 ? 'not-scope' : 'exists-scope'}\"); rd.${k == 1 ? 'addNegation' : 'addExistence'}(scopeRd); return new ${k == 1 ? 'Negation' : 'Existence'}Scope<>(this, scopeRd); }")
        public Object scopeTemplate() {
            return null; // replaced by @PermuteBody
        }

        /**
         * Starts an n-step OOPath traversal chain (root + n-1 steps → TupleN).
         * Call {@code .path(fn, pred)} n-1 times to traverse the chain.
         * Suppressed on Join6Second ({@code when="i < 6"}) — no Join7First exists.
         *
         * <p>Generated method names: {@code path2()} through {@code path6()}.
         */
        @PermuteMethod(varName = "n", from = "2", to = "6", name = "path${n}")
        @PermuteReturn(
                className = "RuleOOPathBuilder.Path${n}",
                typeArgs = "'Join'+(i+1)+'First<END, DS, '+typeArgList(1,i,'alpha')+', BaseTuple.Tuple'+n+'<'+typeArgList(i,i+n-1,'alpha')+'>>,' +' BaseTuple.Tuple'+(n-1)+'<'+typeArgList(i,i+n-2,'alpha')+'>, '+ typeArgList(i,i+n-1,'alpha')",
                when = "i < 6")
        @PermuteBody(body = "{ java.util.List<OOPathStep> steps = new java.util.ArrayList<>(); Object nextJoin = new @PermuteDeclr(type = \"Join${i+1}First\") Join1First<>(end(), rd); return cast(new RuleOOPathBuilder.Path${n}<>(nextJoin, rd, steps, rd.factArity() - 1)); }")
        @SuppressWarnings("unchecked")
        public <@PermuteTypeParam(varName = "m", from = "${i+1}", to = "${i+n-1}", name = "${alpha(m)}") B> Object pathTemplate() {
            return null; // replaced entirely by @PermuteBody
        }

        /**
         * Narrows the last accumulated fact's type parameter at compile time.
         * A pure no-op at runtime — useful when a DataSource uses a base type
         * (e.g., DataSource&lt;Object&gt;) but the actual runtime type is known.
         *
         * <p>Uses the Java varargs type-capture trick: pass no arguments; provide
         * the target type as an explicit type parameter: {@code .<Person>type()}.
         *
         * <p>Example:
         * <pre>{@code
         * builder.from(ctx -> untypedSource)  // DataSource<Object>
         *        .<Person>type()              // narrow to Person
         *        .filter((ctx, p) -> p.age() >= 18)
         *        .fn((ctx, p) -> { });
         * }</pre>
         */
        @SuppressWarnings({"unchecked", "varargs"})
        @PermuteReturn(className = "Join${i}First",
                       typeArgs = "'END, DS, ' + typeArgList(1, i-1, 'alpha') + (i > 1 ? ', ' : '') + 'T'",
                       alwaysEmit = true)
        public <T> Object type(Class<T>... cls) {
            return cast(this);
        }

        /**
         * Captures the current accumulated fact state as a typed extension point.
         * Pass the result to RuleBuilder.extendsRule() to start a child rule that
         * inherits all sources, filters, and constraint scopes up to this point.
         *
         * <p>Uses {@code @PermuteDeclr TYPE_USE} on the constructor to rename
         * {@code RuleExtendsPoint2} to {@code RuleExtendsPoint${i+1}} per permutation —
         * no reflection needed.
         */
        @SuppressWarnings("unchecked")
        @PermuteReturn(className = "RuleExtendsPoint.RuleExtendsPoint${i+1}",
                       typeArgs = "'DS, ' + typeArgList(1, i, 'alpha')",
                       alwaysEmit = true)
        public Object extensionPoint() {
            return cast(new RuleExtendsPoint.@PermuteDeclr(type = "RuleExtendsPoint.RuleExtendsPoint${i+1}") RuleExtendsPoint2<>(rd));
        }

        /**
         * Terminal operation. {@code alwaysEmit=true} prevents boundary omission —
         * RuleDefinition is not in the generated set.
         *
         * <p>Placed on Join0Second so that after {@code not()...end()} or
         * {@code exists()...end()} (which return JoinNSecond), the fluent chain
         * can call {@code fn()} directly. Join0First inherits this via extends.
         */
        @PermuteReturn(className = "RuleResult", typeArgs = "'DS'", alwaysEmit = true)
        public Object fn(
                @PermuteDeclr(type = "Consumer${i+1}<DS, ${typeArgList(1, i, 'alpha')}>")
                Object action) {
            rd.setAction(action);
            return new RuleResult<>(rd);
        }
    }

    /**
     * Template generating Join1First through Join6First.
     *
     * <p>Extends {@code Join0Second<END, DS, A>} — G3 extends clause auto-expansion
     * detects "Join" prefix + embedded number 0 + alpha prefix match, expanding to
     * {@code Join1Second<END, DS, A>}, {@code Join2Second<END, DS, A, B>}, etc.
     *
     * <p>Holds {@code filter()} (single-fact and all-facts overloads). All inherited from
     * the template; inherited {@code join()} and {@code fn()} come from Second via extends.
     */
    @Permute(varName = "i", from = "1", to = "6", className = "Join${i}First",
             inline = true, keepTemplate = false)
    public static non-sealed class Join0First<END, DS,
            @PermuteTypeParam(varName = "k", from = "1", to = "${i}", name = "${alpha(k)}") A>
            extends Join0Second<END, DS, A>
            implements JoinBuilderFirst<END, DS> {

        public Join0First(END end, RuleDefinition<DS> rd) {
            super(end, rd);
        }

        /**
         * All-facts filter — applies a predicate to all accumulated facts.
         */
        @PermuteSelf
        public Object filter(
                @PermuteDeclr(type = "Predicate${i+1}<DS, ${typeArgList(1, i, 'alpha')}>")
                Object predicate) {
            rd.addFilter(predicate);
            return this;
        }

        /**
         * Single-fact filter — applies a predicate to the most recently joined fact only.
         * Suppressed at i=1 via {@code @PermuteMethod} ternary: at arity 1 both overloads
         * would have {@code filter(Predicate2<DS, A>)} — a compile error. The JEXL ternary
         * {@code from="${i > 1 ? i : i+1}"} produces {@code from="2", to=1} at i=1 (empty
         * range), silently omitting this method. At i≥2: from=to=i, one clone per arity.
         */
        @PermuteMethod(varName = "x", from = "${i > 1 ? i : i+1}", to = "${i}", name = "filter")
        @PermuteSelf
        public Object filterLatest(
                @PermuteDeclr(type = "Predicate2<DS, ${alpha(i)}>")
                Object predicate) {
            rd.addFilter(predicate);
            return this;
        }

        /**
         * DSL hint for Rete index optimization. No-op in the sandbox runtime —
         * present for API completeness and migration fidelity with vol2.
         */
        @PermuteSelf
        public Object index() {
            return this;
        }

        /**
         * Binds a variable to the most recently accumulated fact.
         * After this call, v.index() equals rd.factArity() - 1.
         */
        @PermuteSelf
        public <T> Object var(Variable<T> v) {
            rd.bindVariable(v, rd.factArity() - 1);
            return this;
        }

        /**
         * Cross-fact filter using two named variable bindings.
         * V1, V2 are the types of the bound variables — independent of the
         * enclosing class's arity type parameters A, B, etc.
         * Both variables must have been bound via var() before this call.
         */
        @PermuteSelf
        public <V1, V2> Object filter(Variable<V1> v1, Variable<V2> v2,
                                      Predicate3<DS, V1, V2> predicate) {
            rd.addVariableFilter(v1, v2, predicate);
            return this;
        }

        /**
         * Cross-fact filter using three named variable bindings.
         * All three variables must have been bound via var() before this call.
         */
        @PermuteSelf
        public <V1, V2, V3> Object filter(Variable<V1> v1, Variable<V2> v2, Variable<V3> v3,
                                           Predicate4<DS, V1, V2, V3> predicate) {
            rd.addVariableFilter(v1, v2, v3, predicate);
            return this;
        }

    }
}
