package io.quarkiverse.permuplate.example.drools;

import io.quarkiverse.permuplate.Permute;
import io.quarkiverse.permuplate.PermuteDeclr;
import io.quarkiverse.permuplate.PermuteReturn;
import io.quarkiverse.permuplate.PermuteTypeParam;

/**
 * Container for the JoinFirst class family generated by Permuplate.
 *
 * <p>Generated: Join1First through Join6First. Each class holds the accumulated
 * fact sources and predicates and provides:
 * <ul>
 *   <li>{@code join(source)} — advances to the next arity (omitted from Join6First
 *       via @PermuteReturn boundary omission — the leaf node)</li>
 *   <li>{@code filter(predicate)} — arity-preserving; returns {@code this}</li>
 *   <li>{@code fn(consumer)} — terminal; records the action and returns RuleDefinition</li>
 * </ul>
 *
 * <p>join() uses rd.asNext() — an unchecked cast relying on Java's type erasure.
 * Safe because the fluent chain never stores the intermediate type.
 */
public class JoinBuilder {

    /**
     * Template generating Join1First through Join6First.
     *
     * <p>Join6First is the leaf: when i=6, Join7First is not in the generated set so
     * @PermuteReturn boundary omission silently removes join() from Join6First.
     */
    @Permute(varName = "i", from = 1, to = 6, className = "Join${i}First",
             inline = true, keepTemplate = false)
    public static class Join0First<DS,
            @PermuteTypeParam(varName = "k", from = "1", to = "${i}", name = "${alpha(k)}") A> {

        protected final RuleDefinition<DS> rd;

        public Join0First(RuleDefinition<DS> rd) {
            this.rd = rd;
        }

        @SuppressWarnings("unchecked")
        private static <T> T cast(Object o) {
            return (T) o;
        }

        /**
         * Advances the arity by one fact type. Boundary omission removes this method
         * from Join6First — when i=6, Join7First is not in the generated set so the
         * method is silently omitted (leaf node).
         *
         * <p>Uses reflection to instantiate the next JoinFirst class by deriving its
         * name from the current class name (e.g. "Join1First" -> "Join2First").
         * This avoids the broken asNext() unchecked-cast pattern.
         */
        @PermuteReturn(className = "Join${i+1}First")
        public Object join(java.util.function.Function<DS, DataSource<?>> source) {
            rd.addSource(source);
            String cn = getClass().getSimpleName();
            int n = Integer.parseInt(cn.replaceAll("[^0-9]", ""));
            String nextName = getClass().getEnclosingClass().getName() + "$Join" + (n + 1) + "First";
            try {
                return cast(Class.forName(nextName).getConstructor(RuleDefinition.class).newInstance(rd));
            } catch (Exception e) {
                throw new RuntimeException("Failed to instantiate " + nextName, e);
            }
        }

        /**
         * Applies a predicate to the accumulated facts. Returns this — the same
         * JoinFirst instance — allowing repeated filter() chaining at the same arity.
         * when="true" prevents boundary omission (JoinNFirst is always in generated set).
         */
        @PermuteReturn(className = "Join${i}First",
                       typeArgs = "'DS, ' + typeArgList(1, i, 'alpha')",
                       when = "true")
        public Object filter(
                @PermuteDeclr(type = "Predicate${i+1}<DS, ${typeArgList(1, i, 'alpha')}>")
                Object predicate) {
            rd.addFilter(predicate);
            return this;
        }

        /**
         * Terminal operation. when="true" prevents boundary omission — RuleDefinition
         * is not in the generated set so without it, fn() would be silently removed.
         */
        @PermuteReturn(className = "RuleDefinition", typeArgs = "'DS'", when = "true")
        public Object fn(
                @PermuteDeclr(type = "Consumer${i+1}<DS, ${typeArgList(1, i, 'alpha')}>")
                Object action) {
            rd.setAction(action);
            return rd;
        }
    }
}
