package io.quarkiverse.permuplate.example.drools;

import io.quarkiverse.permuplate.Permute;
import io.quarkiverse.permuplate.PermuteDeclr;
import io.quarkiverse.permuplate.PermuteMethod;
import io.quarkiverse.permuplate.PermuteReturn;
import io.quarkiverse.permuplate.PermuteTypeParam;

/**
 * Container for the JoinFirst class family generated by Permuplate.
 *
 * <p>Generated: Join1First through Join6First. Each class holds the accumulated
 * fact sources and predicates and provides:
 * <ul>
 *   <li>{@code join(source)} — advances to the next arity (omitted from Join6First
 *       via @PermuteReturn boundary omission — the leaf node)</li>
 *   <li>{@code filter(predicate)} — arity-preserving; returns {@code this}</li>
 *   <li>{@code fn(consumer)} — terminal; records the action and returns RuleDefinition</li>
 * </ul>
 *
 * <p>join() uses rd.asNext() — an unchecked cast relying on Java's type erasure.
 * Safe because the fluent chain never stores the intermediate type.
 */
public class JoinBuilder {

    /**
     * Template generating Join1First through Join6First.
     *
     * <p>Join6First is the leaf: when i=6, Join7First is not in the generated set so
     * @PermuteReturn boundary omission silently removes join() from Join6First.
     */
    @Permute(varName = "i", from = 1, to = 6, className = "Join${i}First",
             inline = true, keepTemplate = false)
    public static class Join0First<DS,
            @PermuteTypeParam(varName = "k", from = "1", to = "${i}", name = "${alpha(k)}") A> {

        protected final RuleDefinition<DS> rd;

        public Join0First(RuleDefinition<DS> rd) {
            this.rd = rd;
        }

        @SuppressWarnings("unchecked")
        private static <T> T cast(Object o) {
            return (T) o;
        }

        /**
         * Advances the arity by one fact type. The new source type {@code B} is captured
         * as a method type parameter and flows into both the parameter type and the
         * return type — giving a fully typed chain at every arity.
         *
         * <p>{@code @PermuteTypeParam} renames {@code <B>} to the next alpha letter per arity
         * (B at i=1, C at i=2, …). Propagation automatically renames {@code B} in
         * {@code DataSource<B>} alongside the declaration — no {@code @PermuteDeclr} needed.
         *
         * <p>Boundary omission removes this method from Join6First — Join7First is not
         * in the generated set so {@code @PermuteReturn} silently omits join() there.
         *
         * <p>Uses reflection to instantiate the next JoinFirst class by name — necessary
         * because method bodies are not transformed by Permuplate.
         */
        @PermuteTypeParam(varName = "m", from = "${i+1}", to = "${i+1}", name = "${alpha(m)}")
        @PermuteReturn(className = "Join${i+1}First",
                       typeArgs = "'DS, ' + typeArgList(1, i+1, 'alpha')")
        public <B> Object join(java.util.function.Function<DS, DataSource<B>> source) {
            rd.addSource(source);
            String cn = getClass().getSimpleName();
            int n = Integer.parseInt(cn.replaceAll("[^0-9]", ""));
            String nextName = getClass().getEnclosingClass().getName() + "$Join" + (n + 1) + "First";
            try {
                return cast(Class.forName(nextName).getConstructor(RuleDefinition.class).newInstance(rd));
            } catch (Exception e) {
                throw new RuntimeException("Failed to instantiate " + nextName, e);
            }
        }

        /**
         * Applies a predicate to the accumulated facts. Returns this — the same
         * JoinFirst instance — allowing repeated filter() chaining at the same arity.
         * when="true" prevents boundary omission (JoinNFirst is always in generated set).
         */
        @PermuteReturn(className = "Join${i}First",
                       typeArgs = "'DS, ' + typeArgList(1, i, 'alpha')",
                       when = "true")
        public Object filter(
                @PermuteDeclr(type = "Predicate${i+1}<DS, ${typeArgList(1, i, 'alpha')}>")
                Object predicate) {
            rd.addFilter(predicate);
            return this;
        }

        /**
         * Single-fact filter — applies a predicate to the most recently joined fact only.
         * Complement to {@code filter(PredicateN+1)} which tests all accumulated facts.
         *
         * <p>In the generated output this method is named {@code filter} (via
         * {@code @PermuteMethod name="filter"}), overloading the all-facts variant.
         * The sentinel is named {@code filterLatest} to avoid a duplicate method error
         * in the template — both sentinels have {@code Object} parameter type here;
         * after generation they have distinct types and are valid Java overloads.
         *
         * <p>Suppressed at arity 1 via the JEXL ternary: {@code from="${i > 1 ? i : i+1}"}
         * produces an empty range at i=1 (from > to), silently omitting the method.
         * At arity 1, {@code filter(Predicate2<DS,A>)} from the all-facts overload already
         * covers both roles — a second copy would be a compile error.
         *
         * <p>Generated signatures:
         * <ul>
         *   <li>i=1 — omitted</li>
         *   <li>i=2 — {@code filter(Predicate2<DS, B> predicate)}</li>
         *   <li>i=3 — {@code filter(Predicate2<DS, C> predicate)}</li>
         *   <li>i=6 — {@code filter(Predicate2<DS, F> predicate)}</li>
         * </ul>
         */
        @PermuteMethod(varName = "x", from = "${i > 1 ? i : i+1}", to = "${i}", name = "filter")
        @PermuteReturn(className = "Join${i}First",
                       typeArgs = "'DS, ' + typeArgList(1, i, 'alpha')",
                       when = "true")
        public Object filterLatest(
                @PermuteDeclr(type = "Predicate2<DS, ${alpha(i)}>")
                Object predicate) {
            rd.addFilter(predicate);
            return this;
        }

        /**
         * Terminal operation. when="true" prevents boundary omission — RuleDefinition
         * is not in the generated set so without it, fn() would be silently removed.
         */
        @PermuteReturn(className = "RuleDefinition", typeArgs = "'DS'", when = "true")
        public Object fn(
                @PermuteDeclr(type = "Consumer${i+1}<DS, ${typeArgList(1, i, 'alpha')}>")
                Object action) {
            rd.setAction(action);
            return rd;
        }
    }
}
