package io.quarkiverse.permuplate.example.drools;

import java.util.function.Function;

import io.quarkiverse.permuplate.Permute;
import io.quarkiverse.permuplate.PermuteDeclr;
import io.quarkiverse.permuplate.PermuteMethod;
import io.quarkiverse.permuplate.PermuteReturn;
import io.quarkiverse.permuplate.PermuteTypeParam;

/**
 * Entry point for the Drools RuleBuilder DSL approximation.
 * Template class ({@code RuleBuilderTemplate}) generates {@code RuleBuilder} via
 * {@code @Permute(from="1",to="1")} so that {@code @PermuteMethod} can expand the
 * six {@code extendsRule()} overloads from a single template method.
 *
 * <pre>{@code
 * RuleBuilder<Ctx> builder = new RuleBuilder<>();
 * RuleDefinition<Ctx> rule = builder.from(ctx -> ctx.persons())
 *         .filter((ctx, a) -> a.age() >= 18)
 *         .fn((ctx, a) -> System.out.println(a.name()));
 * rule.run(ctx);
 * }</pre>
 */
@Permute(varName = "i", from = "1", to = "1", className = "RuleBuilder",
         inline = true, keepTemplate = false)
public class RuleBuilderTemplate<DS> extends AbstractRuleEntry<DS> {

    @Override
    protected String ruleName() {
        return "extends";
    }

    /**
     * Starts building a rule with its first fact source using a method reference.
     */
    public <A> JoinBuilder.Join1First<Void, DS, A> from(
            Function<DS, DataSource<A>> firstSource) {
        RuleDefinition<DS> rd = new RuleDefinition<>("rule");
        rd.addSource(firstSource);
        return new JoinBuilder.Join1First<>(null, rd);
    }

    /**
     * Starts building a named rule. Returns ParametersFirst which supports all
     * four param styles plus from() to skip params.
     */
    public ParametersFirst<DS> rule(String name) {
        return new ParametersFirst<>(name);
    }

    /**
     * Extends a previously captured rule. Six overloads generated by @PermuteMethod
     * for arities 1..6 (j=2..7 matching RuleExtendsPoint2..7 which carry 1..6 facts).
     */
    @PermuteMethod(varName = "j", from = "2", to = "7", name = "extendsRule")
    @PermuteReturn(className = "JoinBuilder.Join${j-1}First",
                   typeArgs = "'Void, DS, ' + typeArgList(1, j-1, 'alpha')",
                   alwaysEmit = true)
    public <@PermuteTypeParam(varName = "k", from = "1", to = "${j-1}", name = "${alpha(k)}") A>
            Object extendsRule(
            @PermuteDeclr(type = "RuleExtendsPoint.RuleExtendsPoint${j}<DS, ${typeArgList(1, j-1, 'alpha')}>")
            ExtendsPoint<DS> ep) {
        RuleDefinition<DS> child = new RuleDefinition<>(ruleName());
        ep.baseRd().copyInto(child);
        return cast(new JoinBuilder.@PermuteDeclr(type = "JoinBuilder.Join${j-1}First") Join1First<>(null, child));
    }
}
