package io.quarkiverse.permuplate.example.drools;

import io.quarkiverse.permuplate.Permute;
import io.quarkiverse.permuplate.PermuteTypeParam;

/**
 * Container for typed extension point handles produced by JoinNSecond.extensionPoint().
 * Each inner class captures the base rule's RuleDefinition and encodes the accumulated
 * fact types in its type parameters.
 *
 * Naming convention matches Drools vol2: the number = DS + fact count.
 * RuleExtendsPoint2 has 1 fact (A), RuleExtendsPoint7 has 6 facts (A..F).
 *
 * Design: extension is authoring-time deduplication only — extendsRule() copies
 * the base rule's sources and filters into the child at build time. The Rete network
 * handles node sharing automatically; no special runtime concept is needed.
 *
 * Generated by Permuplate: RuleExtendsPoint3..7 are generated from the RuleExtendsPoint2
 * template. RuleExtendsPoint2 itself is kept (keepTemplate=true).
 */
public class RuleExtendsPoint {

    @Permute(varName = "i", from = "3", to = "7", className = "RuleExtendsPoint${i}",
             inline = true, keepTemplate = true)
    public static class RuleExtendsPoint2<DS,
            @PermuteTypeParam(varName = "k", from = "1", to = "${i-1}", name = "${alpha(k)}") A> {
        private final RuleDefinition<DS> baseRd;

        public RuleExtendsPoint2(RuleDefinition<DS> baseRd) {
            this.baseRd = baseRd;
        }

        RuleDefinition<DS> baseRd() {
            return baseRd;
        }
    }
}
