package io.quarkiverse.permuplate.intellij.index;

import com.intellij.openapi.project.Project;
import com.intellij.psi.*;
import com.intellij.util.indexing.FileBasedIndex;
import com.intellij.openapi.vfs.VirtualFile;
import com.intellij.psi.search.GlobalSearchScope;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.Collection;
import java.util.List;

/**
 * Utility facade over both indexes. All plugin components use this class
 * rather than calling FileBasedIndex directly.
 */
public final class PermuteFileDetector {

    private PermuteFileDetector() {}

    /** True if this class is a @Permute template. */
    public static boolean isTemplate(@NotNull PsiClass cls) {
        String name = cls.getName();
        if (name == null) return false;
        return !getForwardValues(name, cls.getProject()).isEmpty();
    }

    /** True if this class was generated by a @Permute template (lives in target/generated-sources). */
    public static boolean isGenerated(@NotNull PsiClass cls) {
        String name = cls.getName();
        if (name == null) return false;
        return !getReverseValues(name, cls.getProject()).isEmpty();
    }

    /** True if this virtual file is under a generated-sources directory. */
    public static boolean isGeneratedFile(@NotNull VirtualFile file) {
        String path = file.getPath();
        return path.contains("/target/generated-sources/") || path.contains("\\target\\generated-sources\\");
    }

    /**
     * For a template class name, returns its PermuteTemplateData (null if not a template).
     */
    @Nullable
    public static PermuteTemplateData templateDataFor(@NotNull String templateSimpleName,
                                                       @NotNull Project project) {
        List<PermuteTemplateData> values = getForwardValues(templateSimpleName, project);
        return values.isEmpty() ? null : values.get(0);
    }

    /**
     * For a generated class name, returns the template class simple name (null if not generated).
     */
    @Nullable
    public static String templateNameFor(@NotNull String generatedSimpleName,
                                          @NotNull Project project) {
        List<String> values = getReverseValues(generatedSimpleName, project);
        return values.isEmpty() ? null : values.get(0);
    }

    /**
     * Returns all template simple names whose memberAnnotationStrings contain the given literal
     * as a substring. Used by the rename processor to find cross-family annotation string refs.
     * Linear scan — acceptable since it only runs at rename time.
     */
    public static Collection<String> templatesReferencingLiteral(@NotNull String literal,
                                                                   @NotNull Project project) {
        List<String> result = new java.util.ArrayList<>();
        FileBasedIndex index = FileBasedIndex.getInstance();
        GlobalSearchScope scope = GlobalSearchScope.projectScope(project);

        index.processAllKeys(PermuteTemplateIndex.NAME, key -> {
            List<PermuteTemplateData> values = index.getValues(PermuteTemplateIndex.NAME, key, scope);
            for (PermuteTemplateData data : values) {
                for (String s : data.memberAnnotationStrings) {
                    if (s.contains(literal)) {
                        result.add(key);
                        return true; // found in this template, move to next key
                    }
                }
            }
            return true;
        }, project);

        return result;
    }

    // --- private helpers ---

    private static List<PermuteTemplateData> getForwardValues(String key, Project project) {
        return FileBasedIndex.getInstance()
                .getValues(PermuteTemplateIndex.NAME, key, GlobalSearchScope.projectScope(project));
    }

    private static List<String> getReverseValues(String key, Project project) {
        return FileBasedIndex.getInstance()
                .getValues(PermuteGeneratedIndex.NAME, key, GlobalSearchScope.projectScope(project));
    }
}
