package io.quarkiverse.permuplate.intellij.editor;

import com.intellij.openapi.fileEditor.FileEditor;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.vfs.LocalFileSystem;
import com.intellij.openapi.vfs.VirtualFile;
import com.intellij.psi.*;
import com.intellij.ui.EditorNotificationPanel;
import com.intellij.ui.EditorNotificationProvider;
import io.quarkiverse.permuplate.intellij.index.PermuteFileDetector;
import io.quarkiverse.permuplate.intellij.index.PermuteTemplateData;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.swing.*;
import java.util.function.Function;

/**
 * Shows a warning banner when opening a generated file:
 * "Generated by Permuplate from Join2.java. Edits will be overwritten on next build."
 * with a "Go to Template" action link.
 */
public class GeneratedFileNotification implements EditorNotificationProvider {

    @Override
    public @Nullable Function<? super FileEditor, ? extends JComponent>
    collectNotificationData(@NotNull Project project, @NotNull VirtualFile file) {
        if (!PermuteFileDetector.isGeneratedFile(file)) return null;

        String templateDisplay = resolveTemplateName(project, file);

        return fileEditor -> {
            EditorNotificationPanel panel = new EditorNotificationPanel(
                    fileEditor, EditorNotificationPanel.Status.Warning);
            panel.setText("Generated by Permuplate" +
                    (templateDisplay != null ? " from " + templateDisplay : "") +
                    ". Edits will be overwritten on the next build.");
            panel.createActionLabel("Go to Template", () -> navigateToTemplate(project, file));
            return panel;
        };
    }

    @Nullable
    private static String resolveTemplateName(@NotNull Project project, @NotNull VirtualFile file) {
        PsiFile psiFile = PsiManager.getInstance(project).findFile(file);
        if (!(psiFile instanceof PsiJavaFile jf) || jf.getClasses().length == 0) return null;
        String className = jf.getClasses()[0].getName();
        if (className == null) return null;
        String templateName = PermuteFileDetector.templateNameFor(className, project);
        return templateName != null ? templateName + ".java" : null;
    }

    private static void navigateToTemplate(@NotNull Project project, @NotNull VirtualFile file) {
        PsiFile psiFile = PsiManager.getInstance(project).findFile(file);
        if (!(psiFile instanceof PsiJavaFile jf) || jf.getClasses().length == 0) return;
        String className = jf.getClasses()[0].getName();
        if (className == null) return;

        String templateName = PermuteFileDetector.templateNameFor(className, project);
        if (templateName == null) return;
        PermuteTemplateData data = PermuteFileDetector.templateDataFor(templateName, project);
        if (data == null) return;

        VirtualFile templateVFile = LocalFileSystem.getInstance()
                .findFileByPath(data.templateFilePath);
        if (templateVFile == null) return;

        PsiFile templatePsiFile = PsiManager.getInstance(project).findFile(templateVFile);
        if (templatePsiFile instanceof com.intellij.pom.Navigatable) {
            ((com.intellij.pom.Navigatable) templatePsiFile).navigate(true);
        }
    }
}
